### ISSUE TITLE
through GM_apiLeakCheck of GM_* api from keyboard events via an iframe

### ISSUE THREAD

**Issue by teramako** [greasemonkey/greasemonkey#1494]
When an UserScript listen keyboard events and then do some operation,
normally cannot execute GM_* apis from content's created event, but events via javascript URL of iframe.src can do.

Test code is here: https://gist.github.com/1565506

UserScript auhors need validate either `aEvent.isTrusted` or not by oneself ?

**Comment by arantius** [comment]
Well, yes.  This is obsolete because there is no more `GM_apiLeakCheck()`.  After I edit the several year old test case to run again, the plain `sendEvent()` works -- it generates a click event, and the click event is handled by the script.  That seems pretty expected.

I've always held that Greasemonkey is for adding functionality and for fixing broken sites.  But never for expressly violating the wishes of the site owner.  If you can't trust the site owner not to generate events, and you react to those events in dangerous ways, then you shouldn't be doing that.
