### ISSUE TITLE
Add support for coffeescript

### ISSUE THREAD

**Issue by mb5** [greasemonkey/greasemonkey#1529]
> CoffeeScript is a little language that compiles into JavaScript. Underneath all those awkward braces and semicolons, JavaScript has always had a gorgeous object model at its heart. CoffeeScript is an attempt to expose the good parts of JavaScript in a simple way. 

It would be nice to write greasemonkey scripts directly in CoffeeScript, it is mich nicer to write and maintain than JavaScript.

**Comment by marnen** [comment]
@weakish Yes, that's really what I was saying. I think `.user.coffee` should Just Work.

**Comment by yi** [comment]
+1 for `.user.coffee`

**Comment by pyhedgehog** [comment]
-1
If it's compiler, it should be run on developer side.

**Comment by cletusc** [comment]
-1.
Coffeescript compiles to native JS, and should continue to be compiled on the script author's side (or use one of the methods described above). Let's say GM implements this, and Coffeescript updates, GM is now responsible for making sure the compiler is up to date and whether a compiler update is backwards compatible otherwise script devs will complain that GM broke their script.

Do it on the dev side, not GM side. It gives you more control as a developer and keeps GM on the path of preferring native solutions over GM-provided solutions.

**Comment by marnen** [comment]
@cletusc @pyhedgehog Really? You want every userscript to have to bootstrap the CoffeeScript compiler, rather than including it once in GreaseMonkey? That might be OK if GM provided for including external libraries (like the CoffeeScript compiler) or other external script files (like the actual CoffeeScript userscript source code), but GM doesn't do that very well (or didn't the last time I looked at doing this -- `@resource` is not adequate).

I assure you that if this were something that could be easily done on the dev side, I would have done it long since. But it isn't, even though it looks like it *should* be until you try it. :) OTOH, it is something that would require only 1-2 lines of code on the GM side (and inclusion of the CoffeeScript compiler as a library) -- I looked into submitting a pull request for it not long ago (though I ultimately didn't have time to do so).

I do understand your concern about GM updating the CoffeeScript compiler and "breaking" existing scripts. But that seems like it would be easy to deal with compared to the current awful workarounds for the lack of `.user.coffee` support.

**Comment by pyhedgehog** [comment]
@marnen No. I want to generate .userjs from .cofee and publish it.

**Comment by flying-sheep** [comment]
not the only workflow. others include using greasemonkeys builtin editor

**Comment by pyhedgehog** [comment]
GreaseMonkey allows you to use any other editor - use one that you can configure to edit source and run compiler.

**Comment by pyhedgehog** [comment]
However there are place for addon to greasemonkey that can precompile `.usercoffee` scripts. And possibly any other addon - i.e. to precompile .userjava with [GWT](http://www.gwtproject.org/). There are place for any addon that use [generator to JS](https://github.com/jashkenas/coffeescript/wiki/List-of-languages-that-compile-to-JS), but why you want to push it to greasemonkey?

However such development can require feature-request for some hooks in greasemonkey such addon can use.

**Comment by marnen** [comment]
@pyhedgehog I wasn't aware that GM supported addons. If that's the case, then that seems like it's probably a much better place for `.user.coffee` support to go.

**Comment by flying-sheep** [comment]
> GreaseMonkey allows you to use any other editor - use one that you can configure to edit source and run compiler.

you don’t understand: this still means that the user will edit the compiled JS code, not the coffeescript source code.

---

about addons: well, could you point us in the direction of APIs that allow such a thing?

**Comment by pyhedgehog** [comment]
As far as I know it doesn't. But anyone can write Fx addon that uses GM objects and functions.
So I propose to investigate such addon requirements and convert this issue to request for needed hooks and exported functions.

**Comment by flying-sheep** [comment]
why should there be a .user.coffee nearby if the script was obtained via some userscript hoster?

sorry, but nothing will be as convenient as simply handling .user.coffee in greasemonkey.

**Comment by pyhedgehog** [comment]
Why you need to edit script you have obtained via some userscript hoster?

There are two different workflows - developer and user. User should get compiled version (i.e. `.userjs` file). Developer should be able to configure it's own testing/development environment to edit source (any source - [coffeescript](http://coffeescript.org/), [livescript](http://livescript.net/), [toffeescript](https://github.com/jiangmiao/toffee-script), [ruby](http://rubyjs.org/), [python](http://pyjs.org/) or any other). You want GM to integrate them all? Let's start with [Blockly](https://developers.google.com/blockly/)?

**Comment by flying-sheep** [comment]
> There are two different workflows - developer and user.

wrong, i often tweak scripts i have downloaded. and i don’t want to fork a repo, figure out the build system, and then start editing.

> You want GM to integrate them all?

of course not. coffeescript and maybe babel should be more than enough (remember: this is about conveniently editing *small* userscripts, not big applications where type safety would be beneficial)

**Comment by pyhedgehog** [comment]
Why you think it should be inside GM? Why not another addon?

**Comment by flying-sheep** [comment]
if that’s feasible and GM offers the required API hooks, fine, but i’m going to have to see that before agreeing that it’s the best alternative.

**Comment by joech4n** [comment]
Does the code provided in https://github.com/greasemonkey/greasemonkey/issues/1529#issuecomment-68106365 work for still work for anyone else? I can't seem to be able to get it to work.
