### ISSUE TITLE
"@grant none" (or auto-detected none) combined with JQuery == Bad News

### ISSUE THREAD

**Issue by arantius** [greasemonkey/greasemonkey#1614]
https://groups.google.com/d/topic/greasemonkey-users/ne90b8Lea_Q/discussion

> I saw a lot of complaints on the addons page about how scripts that `@require`
> jquery weren't working.  I started encountering the same issue when I got
> upgraded last night.  At first, I thought that it was RES (Reddit Enhancement
> Suite) that was causing the problems, but it turns out that it was a small
> script that I had written that was also running.  This is the problem in short:
> 
> When using `@grant` none, or auto-detect with no GM_\* functions, the `@require`d
> version of JQuery is stomping on the one that's loaded in the "unsafeWindow"
> namespace (because they're now the same).  By adding a simple `@grant GM_log`,
> all of the problems disappear because JQuery is being loaded in the sandboxed
> window.
> 
> So, either all scripts need to add a `@grant` line to continue working, or
> the new auto-detection needs to be reconsidered.  IMO, continuing with the old
> behavior and only using the unsandboxed behavior when `@grant none` is
> specified seems to be the best idea for backwards compatibility. 

Which disagrees with my findings in #1557 but needs to be checked.

**Comment by DanKaplanSES** [comment]
@johan 

> I think the proper change needed for a jQuery-using script is to wrap itself in
> 
> ```
> `jQuery.noConflict(true)(function() {
>   // code here, possibly with a leading "var $ = jQuery;" too
> });
> ```
> 
> [source](https://github.com/greasemonkey/greasemonkey/issues/1614#issuecomment-8101628)

I agree, but I would make one minor change: passing `$` into the callback. So it would look like this:

```
jQuery.noConflict(true)(function($) { // note the $ parameter
  // ...
});
```

That way, you don't need to worry think about a leading `var $ = jQuery;`, as far as I understand it. Actually, I'm a little lost in this conversation after [your comment](https://github.com/greasemonkey/greasemonkey/issues/1614#issuecomment-8101628). Is there a reason something [this example isn't in the wiki](https://wiki.greasespot.net/index.php?title=Third-Party_Libraries#Potential_conflict)? I'm guessing it's because it's user generated and the author came up with that solution independent of this thread, but I'm asking in case there is a flaw with this example code. 

---

As an aside, I'd be happy to edit https://wiki.greasespot.net/index.php?title=Third-Party_Libraries if your example is the better solution, but I don't think it's possible to edit that wiki: I can sign up, but it requires me to verify email before I edit, and the sign-up page/preferences doesn't have an email field.
