### ISSUE TITLE
Enable manual update on modified userscripts

### ISSUE THREAD

**Issue by nstepien** [greasemonkey/greasemonkey#1743]
Sure, prevent it to be automatically updated if you want, but let me manually update it via the context menu!

**Comment by darkred** [comment]
What about enabling update for modified scripts via

1. wrench-drop-down>check for updates and via 
2. FIrefox automatic checking for updates?

Currently, if you modify a script, then updating for it gets disabled
(there's no `Automatic updates:    Default/On/Off` radio buttons on any script anymore
when you doubleclick then in Addons Manager)
and you only can update it via "forced find update" .

I suggest, whenever there's a new version available for a modified script,
the script to become uploaded,
and the user to get a relevant notification about it
(that the script x that was previously locally modified, has been updated,
instead of the standard "script x has been updated").

**Comment by Darker** [comment]
Why was this closed? It's really something I need to quickly update my script from git.

**Comment by GWuk** [comment]
@Darker: edit file locally (i.e. add comment), then "Forced Find Updates" is available in script's context menu

**Comment by stonecrusher** [comment]
Erm this is gone again with GM4, right? At least I can never see scripts in the addons manager and the script menu always just says `enabled` `edit` and `uninstall`.

**Comment by Eselce** [comment]
(Auto) update is still in the work. Not yet there...

**Comment by Eselce** [comment]
Here's an anchor for that... #2531

**Comment by Eselce** [comment]
(and even a duplicate #2667)

**Comment by stonecrusher** [comment]
Thank you @Eselce .
I wasn't sure if it automatically updates in the background without notice so I had different search terms.
