### ISSUE TITLE
A script tag injected into a page with a Content Security Policy that rejects inline scripts will not run [WORKING AS INTENDED]

### ISSUE THREAD

**Issue by ugawk** [greasemonkey/greasemonkey#2046]
Reduced test script:

// ==UserScript==
// @name        Hello World
// @description Hello World
// @include     *
// @version     1.0
// @grant       none
// ==/UserScript==
var script = document.createElement('script');
script.textContent = "(alert('hello'))()";
document.body.appendChild(script);

This script doesn't work on
https://github.com/greasemonkey/greasemonkey/issues

On every other page it works and alert box pops up. Is this a bug with greasemonkey?

**Comment by janekptacijarabaci** [comment]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=866522 .

**Comment by mikhoul** [comment]
@arantius   It should work look here: http://i.imgur.com/Kmx7yX9.png  


 

> Implementation Considerations
> 9.1. Vendor-specific Extensions and Addons
> 
> Policy enforced on a resource **SHOULD NOT** interfere with the operation of user-agent features like **addons, extensions, or bookmarklets**. These kinds of features generally **advance the user’s priority over page authors,** as espoused in [HTML-DESIGN].
> 
> Moreover, applying CSP to these kinds of features produces a substantial amount of noise in violation reports, significantly reducing their value to developers.
> 
> Chrome, for example, excludes the chrome-extension: scheme from CSP checks, and does some work to ensure that extension-driven injections are allowed, regardless of a page’s policy.

Direct link:  https://www.w3.org/TR/CSP3/#extensions

Do you think you can do do something about it @arantius  ?

**Comment by pyhedgehog** [comment]
@arantius, code parts can be surrounded by [backticks](https://guides.github.com/features/mastering-markdown/#examples).
@ugawk, can't [userCSP](https://addons.mozilla.org/en-US/firefox/addon/newusercspdesign/) helps?

**Comment by mikhoul** [comment]
@pyhedgehog   Does userCSP permit to change relax CSP rules on site like Tweeter or Github ?

**Comment by pyhedgehog** [comment]
Seems it's not updated for newer Fx.

**Comment by mikhoul** [comment]
I will try it next week when I will be a little bit less busy to see how it work.

It would really be useful if we can't bypass CSP based on website for power users. 

Disabling it for all site is to dangerous IMO, I know that on Chrome there is at least 2 addons to disable CSP based on domain name: https://chrome.google.com/webstore/detail/disable-content-security/ieelmcmcagommplceebfedjlakkhpden  AND https://chrome.google.com/webstore/detail/content-security-policy-o/lhieoncdgamiiogcllfmboilhgoknmpi

It would be really useful id @arantius integrate it in GM for power users since being able to control Userscript and addons fully is part of the **_W3C Working Draft, 21 June 2016_**.


Regards :smile:

**Comment by janekptacijarabaci** [comment]
See also:
http://stackoverflow.com/questions/19264831/how-to-add-content-security-policy-to-firefox-extension

The testing branch:
https://github.com/janekptacijarabaci/greasemonkey/tree/_testBranch_csp

**Comment by mikhoul** [comment]
@janekptacijarabaci    How I can test your fork ?   I  don't see any new release.  :question: 

_BTW_: **Big Thanks** for "fixing" the CSP to be able to put inline script in all website.   I will be able to use back the web as I  like it :smile:  

Regards !

**Comment by janekptacijarabaci** [comment]
@mikhoul
See (e.g.)
http://www.linuxquestions.org/questions/linux-software-2/how-to-edit-files-inside-of-xpi-or-unpack-change-and-pack-again-911534/

All (i.e. changed) files are in the separate pack (see above "..._testBranch_csp")
\- "Clone and download" => "Download ZIP"

**Comment by mikhoul** [comment]
@janekptacijarabaci   

Thanks a lot for the help !  :smile: 

I'm not familiar with Github except to leave comment and other basic things.

I can do many things in JS but I never took a basic course to know the fundamentals... so sometime I lost lot of time to understand basic things.  My next goal is to stop and follow a basic JS course online to stop to be stuck with basic issues ;-) 


How I can know if your fork will be integrated in the main branch ?  Like I told you I'm not familiar with Github over "basic" use.  I'd like to be able to follow to know when you will make an update to apply it on my side.  

Right now I applied it on the top of the latest beta, if I see something "wrong" I will let you know, later this week after I will finish a project I will have more time to test the CSP on site that restrict "inline JS".

Thanks again for your time, it's really appreciated. :yum:

**Comment by janekptacijarabaci** [comment]
> How I can know if your fork will be integrated in the main branch ?
Maybe never added... :-)
It's not my decision...

**Comment by mikhoul** [comment]
@janekptacijarabaci  Will you update your fork ?   I'd don't mind to update manually the XPI but I 'd like to know when you update your version :laughing: 

Regards !   🐸

**Comment by janekptacijarabaci** [comment]
This will not be added to my fork. This is just a thing for testing.

**Comment by mikhoul** [comment]
@janekptacijarabaci  Is there a way I can add it "safely" manually at each future release ? 

If you can provide me the steps to "inject" the change that allow CSP to be allowed I would be grateful. 
This way I could add/inject it at each release myself  😇


Regards !

**Comment by janekptacijarabaci** [comment]
I don't know how to describe the steps (which are both simple and safe) to do it (for all future versions).

But... (this is true only for this moment!):
You can replace this file (modules/requestObserver.js) with the new file from the test branch.

__Hovewer, if you use it, you do it at your own risk!__

Through we are very off-topic...

**Comment by mikhoul** [comment]
@janekptacijarabaci     Thanks a lot for the information !    

It should give me enough time to learn how the code work to integrate the code directly in my script. 

Will have lot to study but I like to learn and I have already bookmarked the stackoverflow "question" too.

Thanks again ! :+1: 

Regards !

**Comment by the8472** [comment]
> I do not believe there is a way to securely disable CSP only for certain scripts. Look at the example in the original report. There is no request nor response to set a header on.

Dynamically registering `greasemonkey-script:` URIs and then injecting them may provide a limited CSP bypass. Custom URL schemes should be able to bypass CSP, webextensions use one too.

1. Fetch resources with GM_XHR with a `Blob` result
2. turn blob into greasemonkey-uri
3. inject DOM `<img src="greasemonkey-script:...">`

I think it is important to provide ways to bypass CSP, otherwise site admins get too much control and can block userscripts from effectively loading any content. Since CSPs can block data: and blob: URIs too even quasi-local content doesn't work.

**Comment by mikhoul** [comment]
> I think it is important to provide ways to bypass CSP, otherwise site admins get too much control and can block userscripts from effectively loading any content. 

@the8472 I agree 200%, I will study it this fall to have a better understanding.

This addon on Chrome seem interesting too:  https://github.com/Rufflewind/chrome_cspmod

This script too but to much advanced for me: https://github.com/warren-bank/moz-rewrite

**Comment by janekptacijarabaci** [comment]
See also https://github.com/greasemonkey/greasemonkey/pull/2420

My suggestion is completely different with his. It's practically the same as:
https://bugzilla.mozilla.org/show_bug.cgi?id=866522#c71

**Comment by mikhoul** [comment]
Thanks @janekptacijarabaci for the links I subscribed to #2420 to follow the discussion.

I really hope we can agree on something useful for the greasemonkey community regarding the CSP. :pray:

**Comment by allo-** [comment]
Can the extension add csp rules? Then it could try to add a rule to allow scripts with the hash of the greasemonkey script (this is, what CSP sees as "safe inline").

**Comment by lainverse** [comment]
@janekptacijarabaci suggested to post it here, so here is my concept of safe CSP-bypassing API for inline scripts:

The idea is to add script-src with list of random 'nonce-...' values to each request with CSP. There should be as many nonces as scripts which require this API since they are one-time use only and multiple scripts can't use same nonce within same context.

Example:
```
...
// @grant GM_getNonce
...
var scr = document.createElement('script');
scr.setAttribute('nonce', GM_getNonce());
scr.textContent = 'console.log("test");';
document.body.appendChild(scr);
...
```

For each script with `@grant GM_getNonce` GM should generate unique random number per context where it runs with something like:
```
var array = new Uint32Array(numberOfScripts);
crypto.getRandomValues(array);
```
GM_getNonce() should return number assigned to a script in specific context.

This way we can have secure inline scripts without compromising existing security on the page since number will expire as soon as it will be used once. It could be a good idea to restrict this API to scripts with `@run-at document-start` only to make sure script author had enough time to inject his code before scripts on the page had chance to run.

Another way to implement this is to provide an API to register one or more sha256/sha512 hashes with something like: `// @CSPHashList  sha256-..., sha256-..., ...`
This way script authors will provide list of hashes of their scripts which they are going to inject into a page, but this won't let dynamic inline code and any change in existing code will require updating hash list.

**Comment by the8472** [comment]
That could be extended to all CSP `*-src` things since GM scripts also may want to add inline stylesheets, images etc.
Especially since GM_addStyle() does nothing more than adding a `<style>` tag, as opposed to using the stylesheet service to add a more privileged one.

As further complications CSPs may also contain `require-sri-for` and `sandbox` directives. The latter one can completely disable scripts with no exceptions.

**Comment by lainverse** [comment]
As I understand 'require-sri-for' could be resolved with my second proposition by providing a list of hashes to register. There should be sections per resource type, though. Also, isn't it possible to add 'allow-scripts' after 'sandbox' if there are none and then forbid downloading/running all scrips, but added with nonce/hash? Not sure will it be the same. On the other hand normally `sandbox` CSP is very rare. Especially without `allow-scripts` after it. Not sure if it worth dealing with it at all.

**Comment by the8472** [comment]
Well, I guess people wouldn't really need inline scripts anyway if the page has no scripts on it own, they can just execute things in the GM sandbox.

**Comment by idiotWu** [comment]
Ran into same issue when I was trying creating a web worker from blob url (`blob://`) on Twitter. So I'm afraid @lainverse's suggestion might not work for me because we can't add `nonce` attribute to worker scripts :(

**Comment by idiotWu** [comment]
Possibly not. The request to fetch worker script is send from browser, so we have nothing to do with it.

Currently I am using another extension to modify CSP headers, but I don't think it's a good idea to bypass sites' security restrictions like this.

**Comment by allo-** [comment]
What is the problem with nonce (not a sri hash)? You inject a nonce for each script/style into the CSP-Header and use the nonce with the injected script/style tags.

**Comment by idiotWu** [comment]
@allo- yep, but worker scripts are loaded via `new Worker(url)`, not script tags. Since it's a native DOM API, I am not able to add a `nonce` to it.

**Comment by lainverse** [comment]
Wouldn't `worker-src sha256-...` work? You won't be able to put generated code like this, but if script for worker is static this should work.

**Comment by idiotWu** [comment]
Just tried but still failed, I think hashes [only work for inline scripts.](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#Unsafe_inline_script)

**Comment by allo-** [comment]
You do not use hashes for inline scripts, as somebody who can inject a script, can inject the matching hash. So it needs a nonce. On the other hand, there is SRI for external scripts and url-based rules.

> Wouldn't worker-src sha256-... work? You won't be able to put generated code like this, but if script for worker is static this should work.

I think the security considerations are the same as for the website owner himself: If you want to use a static worker, a hash or nonce work, if you need dynamic ones, you need to be more liberal with the CSP rules. Somebody who writes a script needs to consider the same things as the website owner.

Respecting the owners CSP to a level, which makes it impossible to script the site is against the idea of greasemonkey, which should implement features, which aren't supported by the owner. So I think some CSP rules should be disabled, if it won't work otherwise.

**Comment by mikhoul** [comment]
> Currently I am using another extension to modify CSP headers,

@idiotWu  Which extension do you use ? 

Regards :octocat:

**Comment by idiotWu** [comment]
@mikhoul [Content Security Policy Override](https://chrome.google.com/webstore/detail/content-security-policy-o/lhieoncdgamiiogcllfmboilhgoknmpi), an extension for Chrome browser. The following is my configs:

```json
[
  ["https://twitter\\.com/*", [
    ["worker-src|$", "worker-src 'self' blob:"]
  ]]
]
```

**Comment by lainverse** [comment]
Hm... So, no plans to implement any methods to bypass CSP?
And what is that "Bankruptcy" milestone is anyway?

**Comment by Swyter** [comment]
This sucks. Closing it is the easy way out instead of figuring out a problem is is only get worse as more sites start to use CSPs. It's pretty clear that there's a need for it, don't ignore it.

**Comment by nyuszika7h** [comment]
Apologies if this has been mentioned in this thread already, but FYI,
anyone who needs CSP support can use Tampermonkey, which already handles
this.

**Comment by Sxderp** [comment]
Just as an update. For anyone following. The Mozilla folks had their sights on allowing this for a [couple years](https://bugzilla.mozilla.org/show_bug.cgi?id=1267027) now. Accordingly, some new patches have been pushed, [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1406278) and [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1407056), which should resolve these issues. Unfortunately they're set for merging into the Firefox 58 branch.

**Comment by rslifka** [comment]
@jerone @arantius The main reason one might want to do this is to iterate quickly on your own code included in `@require` directives. It's difficult to engineer a UserScript when a well-factored codebase means not placing your entire source in a single file 😄 

* Not placing your code in a single file means using a `@require` directive to include it...
* Which caches it...
* Which means you can't update it once you've shipped it.

This problem is exacerbated during development:

1. Write your code in your fully-featured, customized editor you've worked with for years (i.e. not the native *Monkey editor)
1. CTRL-A, CTRL-C
1. Switch to Chrome
1. Select GreaseMonkey tab with editor open
1. CTRL-V
1. Select application tab
1. Refresh

It's a pretty painful workflow.

Dr Nic. [wrote about this](http://drnicwilliams.com/2009/06/07/tdd-for-greasemonkey-scripts-and-introducing-ninja-search-js/) nearly ten years ago, before the proliferation of CSPs so his approach worked back then. I can't think of a way to do it now since there's no way to include an external resource and there's no way to invalidate the GM cache that I've been able to find.

Any advice here?

Thanks!

**Comment by rslifka** [comment]
@nyuszika7h I'm using TamperMonkey and getting this error. Is there a workaround?

```
VM2847:22 Refused to load the script 'https://openuserjs.org/src/libs/sizzle/GM_config.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' https://apis.google.com https://www.google-analytics.com ...
```

**Comment by jsamr** [comment]
@arantius  
A folk on [this bugzilla ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=1267027) suggested to use contentScripts API to bypass CSP restrictions.

> Can’t you use the the `contentScripts` API¹?
> ¹ https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/contentScripts

**Comment by Cerberus-tm** [comment]
@rslifka A bit belatedly: isn't the conventional solution to include the version number in the name of the @require file, like the way Jquery and simiar .js files are dealt with by Google and others? So, when you change the @require file, you change the version number in the name of the file and upload it; and you change the file name in the @require line in the main script accordingly. So the updated main script will automatically download the new version of the library file.

**Comment by rslifka** [comment]
@Cerberus-tm yep, still a pretty onerous workflow to go through all those steps when developing locally :)

I've solved this by having a development-mode UserScript that references file:// URLs, and enabled local file access in TamperMonkey in the Chrome extension settings. Works great!

**Comment by Cerberus-tm** [comment]
@rslifka Ah, that sounds smart. I wonder whether this would also work with Greasemonkey in Firefox.

**Comment by ajloveslily14** [comment]
> Apologies if this has been mentioned in this thread already, but FYI, anyone who needs CSP support can use Tampermonkey, which already handles this.

How does it handle it? I can't seem to find any documentation for it and it is causing me issues...

**Comment by piratesephiroth** [comment]
> 
> 
> > Apologies if this has been mentioned in this thread already, but FYI, anyone who needs CSP support can use Tampermonkey, which already handles this.
> 
> How does it handle it? I can't seem to find any documentation for it and it is causing me issues...

I believe they're talking about the option at the bottom of the advanced settings.

**Comment by ajloveslily14** [comment]
> > > Apologies if this has been mentioned in this thread already, but FYI, anyone who needs CSP support can use Tampermonkey, which already handles this.
> > 
> > 
> > How does it handle it? I can't seem to find any documentation for it and it is causing me issues...
> 
> I believe they're talking about the option at the bottom of the advanced settings.

Ah, I found the setting and it's enabled. Still having issues though...
