### ISSUE TITLE
User Scripts display order not remembered in about:addons

### ISSUE THREAD

**Issue by CheriMDixon** [greasemonkey/greasemonkey#2127]
You can sort by Status, Name, or Execution Order, but once you leave about:addons and come back later, your preferred sorting is no longer set. Please remember the user's sort selection.

Thanks! :-)

**Comment by roger21** [comment]
also it would be nice have a drag and drop system to order them (execution order) because the current system (earlier/later) is really tedious when you want to order any new script inside a long list .... well actually i just remembered i just edit the config.xml from now ... so, there's an easy way still

**Comment by CheriMDixon** [comment]
Thanks, janekptacijarabaci!

**Comment by arantius** [comment]
Got fixed by 55820c14de40c8c5bdd575e20f7e628cac2ab278 in 3.4.
