### ISSUE TITLE
[FEAT] allow running scripts on document url change

### ISSUE THREAD

**Issue by akostadinov** [greasemonkey/greasemonkey#2136]
Hello, this feature request is related to #2135 and #1970. I think that there are valid use cases a script wants to run when page url changes regardless of the way it changes. I see numerous questions in stackoverflow about this topic. Two good examples [1][2].

My particular use case is that I redirect any attempt to open video on facebook to the mobile version to allow HTML5 player instead of flash [3]. The solutions available in the stackoverflow answers are really suboptimal and IMHO deserve greasemonkey support. Any scripts wanting to redirect to another page are hard to implement. It seems now many sites are using HTML5 functions to change page location and it's likely more and more scripts to be affected and not be run as authors expect.

I think it makes most sense to allow script authors to hook to different event types. For most redirects I think having an option `@run-at url_change` would do the job. It might be also useful to have `@run-at page_loaded_after_urkl_change`. In the former example the script would be run immediately when browser sets new location. And in the latter example, script would be run when page is loaded after location has been changed by browser for whatever reason (be it page reload or ajax call).

I hope this makes sense.

[1] http://stackoverflow.com/questions/18989345/how-do-i-reload-a-greasemonkey-script-when-ajax-changes-the-url-without-reloadin
[2] http://stackoverflow.com/questions/7381367/why-greasemonkey-doesnt-detect-some-page-changes-in-facebook
[3] https://greasyfork.org/en/scripts/8176-switch-to-mobile-version-on-facebook-video-page

**Comment by arantius** [comment]
You can already do this.  https://developer.mozilla.org/en-US/docs/Web/Guide/API/DOM/Manipulating_the_browser_history#The_popstate_event

The chances that running the entire script again is the right thing to do is small.  The chances that the author can hook and respond correctly tho this event are much higher.

**Comment by akostadinov** [comment]
I don't see this working. I have the following in the script:
```
unsafeWindow.onpopstate = function(event) {
  alert(event.state)
  if(event.state.indexOf("https://www.facebook.com/video.php?v=") > -1) {
    var target = content.document.location.href.replace("www.facebook", "m.facebook");
    window.location.replace(target);
  }
};
```
I have the `@grant` line. And I don't see any alerts clicking through facebook. IMHO this deserves greasemonkey core support to also make it cross browser compatible.

**Comment by jerone** [comment]
Maybe this will help you: https://gist.github.com/jerone/e38e8637887559870d84

**Comment by akostadinov** [comment]
Thank you but I don't see how can I use it. I use:
```
...
// @grant none
...
window.onpopstate = function(event) {
  // alert(event.state);
  alert(event.URL);
  alert(history.state.URL);
  alert(history.state);
  alert(content.document.location.href);
  if(event.state.indexOf("https://www.facebook.com/video.php?v=") > -1) {
    var target = content.document.location.href.replace("www.facebook", "m.facebook");
    window.location.replace(target);
  }
};
```

I never get the target url, only the source url. As far as I see it would require some complicated handling. Would be much easier if greasemonkey offers a convenience. I don't think it's only about my simple use case.

**Comment by akostadinov** [comment]
I have some more observations, hope it helps somebody. First currently greasemonkey is not very useful if you want to implement a simple redirect based on URL. I don't see any reasonable way to achieve it because on document-start does not trigger on each url change. And document-end is often slow. So I still believe the best option is to have another `@run-at` value that triggers whenever url changes.

Another thing I notice is that `window.location.replace(target)` does not always work. I've no freakin' idea why... when I reload the page it works but without reload it often does no effect. By inserting alert calls I saw that the code is run but page is not reloaded with the new URL. Calling `reload()` also does not seem to have any effect whatsoever... now I'm just starting to see what web library writers are faced with - some crazy APIs that have so many edge cases it's some hell...

**Comment by jerone** [comment]
Did you tried running above code in the Developer Tool first before blaming GreaseMonkey?

From https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onpopstate
> Note that just calling history.pushState() or history.replaceState() won't trigger a popstate event. The popstate event is only triggered by doing a browser action such as clicking on the back button (or calling history.back() in JavaScript). And the event is only triggered when the user navigates between two history entries for the same document.

**Comment by akostadinov** [comment]
I was very clear that this is a feature request to make greasemonkey run scripts upon URL change, no matter how window url/location has changed. I'm not complaining greasemonkey is guilty for how events change. It's a decision of greasemonkey maintainers to implement or not this feature. I'm just leaving some info for others searching for similar info (and based on stackoverflow such people seem to exist).
And yes, I've read the above paragraph but left feedback on your proposed solution to my issue. Thought that maybe it could work somehow. Maybe you thought I'm blaming greasemonkey with "some crazy APIs". That was directed at browsers.
Anyway, I don't have the nerves, this is not my job, I'm leaving it for the people that really need to figure it out.

**Comment by C0MPAQ** [comment]
I am much disappointed like akostadinov, in people here who avoided answering to the feature in question.

I wrote the user script https://openuserjs.org/scripts/C0NPAQ/Youtube_Channel_Playlist . It works only by replacing the current URL. There are probably hundreds of google results, by people doing the same: not answering the proper question.

I realize that this is a developer request, not a forum to answer questions.

Regardless, its extremely frustrating, mostly in the OpenSource community. Forum threads are marked as "solved" although the problem was never "solved", it was merely forgotten or evaded.

Please consinder answering this feature request properly. A mere "maybe doesn't work in Browser X, we don't consider implementing it yet" (assumably chromium/Chrome), would have sufficed...

**Comment by winneon** [comment]
I'm going to follow up with what @C0MPAQ said and absolutely agree. If you're going to say no, say no. Don't avoid the request. It's not hard to say no. Give us a reason why you're not doing it, it could be anything, just don't avoid the request. This is important to all of us.

**Comment by Sxderp** [comment]
I thought @arantius response back in 2015 was fairly clear. The request wasn't being considered for implementation then. And _probably_ still isn't now.

As for a reason, not sure about back then. But now? Well, there's a bunch of other things that still need doing.

For myself (note, I'm no maintainer, I just lurk around here), I'd consider the request, though I'd add it as a separate `@run-at` or somesuch. Due to the nature of this feature it'd never get any potential benefits of #2663, and it would be easier to separate scripts that couldn't be managed through that interface using some static flag / identifier.

---

Looking at the script @C0MPAQ wrote, looks like it uses `window.location.replace` and adds some parameters into the query string. If I'm not mistaken doesn't that cause a navigation / resource load of the page and thus re-execute the script anyway? The original request was about running the script when the URL changed _without_ causing a navigation / resource load. Which, unless I'm mistaken[1], can only be done using `window.history.pushState`, no?

By that, a potential solution is to  override `window.history.pushState` in a `@run-at document_start` (disregarding any current issues with execution timing) script.

[1] You can change the hash (anchor) of a url without a navigation, but that's easily caught using `window.onhashchange`.
