### ISSUE TITLE
Greasemonkey sync failed to apply records

### ISSUE THREAD

**Issue by turtleloveshoes** [greasemonkey/greasemonkey#2188]
https://support.mozilla.org/en-US/questions/1062235
https://pastebin.mozilla.org/8833703
GreaseMonkey Lines 73-100

Troubleshooting tried: 
Disabling each of the components, re-attaching the account, cookies are enabled, local storage is enabled. 

It looks like this user is on the new sync due to : 
First looking at the two versions of sync mentioned: 
>1430717298226   Sync.Service       DEBUG  User-Agent: Firefox/37.0.1 >FxSync/1.39.0.20150405003226.

then later
>1430717309618   Sync.Collection    DEBUG       mesg: POST success 200 https://sync-197-us-west-2.sync.services.mozilla.com/1.5/19109881/storage/forms

Is it expected for the new sync to support the greasemonkey scripts? 
And do these need to be manually enabled for them to work? 

services.sync.prefs.sync.extensions.greasemonkey.sync.enabled 
extensions.greasemonkey.sync.enabled and went to true,  extensions.greasemonkey.sync.enabled.lastSync, extensions.greasemonkey.sync.enabled.lastSyncLocal and extensions.greasemonkey.sync.enabled.syncID.

**Comment by arantius** [comment]
The critical bit would appear to be:

```
1430717301767   Sync.Store.Greasemonkey    WARN        Failed to apply incoming record b46402b09fa7682e8a3a240d3c0314c2e290cd8e
1430717301767   Sync.Store.Greasemonkey    WARN        Encountered exception: TypeError: matches is undefined (resource://greasemonkey/script.js:229:18) JS Stack trace: 
Script_setUserMatches@script.js:229:19 
< ScriptStore.prototype.update@sync.js:206:7 
< Store.prototype.applyIncoming@engines.js:338:7 
< Store.prototype.applyIncomingBatch@engines.js:304:9 
< doApplyBatch@engines.js:973:32 
...
```

So [that line](https://github.com/greasemonkey/greasemonkey/blob/4d5039598c8f929da89477334ebcae5cc1444a80/modules/sync.js#L206) is referencing a bad value.

**Comment by arantius** [comment]
User matches were [just added](https://github.com/greasemonkey/greasemonkey/blame/4d5039598c8f929da89477334ebcae5cc1444a80/modules/sync.js#L206) so it's no surprise that a sync record is possibly them.

**Comment by janekptacijarabaci** [comment]
I'm sorry, my mistake, I missed it.

**Comment by arantius** [comment]
It happens to the best of us.

**Comment by arantius** [comment]
I'm trying to replicate this.  I've got:

* My normal dev profile ("main"), nightly Firefox, latest Greasemonkey, signed in to my (new) Sync test account.
* A second otherwise blank profile ("test"), also signed into the same Sync account.

Sync preferences has everything **but** Add-ons checked.  I installed Greasemonkey 3.0 in the test profile and the only script installed in the main profile installed itself by Sync.  Uninstalled every script everywhere and completed several manual Sync actions until everything was settled.

In the test profile, running a pre-user-matches Greasemonkey, install one script.  Test sync, main sync, main sees `TypeError: matches is undefined` error.  But the script is installed.  Ugh, that means reproducing is a long uninstall everywhere/sync/sync/install/sync process.  But it is at least reproduced.

Trying to uninstall this script in main and then Sync in test produces a disabled, not uninstalled, script, as well.  That's probably #2186?
