### ISSUE TITLE
https websites

### ISSUE THREAD

**Issue by hartman** [greasemonkey/greasemonkey#2198]
Is it correct that if you want a script to load on https resource, that you need to add an explicit @grant for the GM functions it wants to use ?

Apparently a lot of GM scripts 'broke', because Wikipedia switched to HTTPS-only... 
Was this difference between http and https always there ? is it a bug ? Just looking for more background.

**Comment by arantius** [comment]
No, there is no relation between HTTPS and `@grant`.  If anything probably the `@include` patterns is what broke.

**Comment by hartman** [comment]
Nope, we explicitly tested this. Try using the following fragment on English Wikipedia:

**Comment by cletusc** [comment]
This is the way `@grant` works. If you don't `@grant` the `GM_*` API, it will fail (`GM_* is undefined`), regardless of http or https. When running that script, I get the following:

![](http://i.imgur.com/DTnflMB.png)

Please check your browser console and it'll point out the problems. According to [the wiki](http://wiki.greasespot.net/@grant), since GM 2.0, `@grant` would assume `none`, although I believe there was smart detection still automatically trying to add the correct `@grant`. Even still, since GM 2.0, you should be explicitly `@grant`ing the APIs that you use.

**Comment by hartman** [comment]
Well the user reported that it worked before and didn't anymore after we turned on https-only. Interpreting what you stated, that must then mean that there is a difference in how the smart detection works, for some vague reason that no one wants to support.

I'm fine with that answer, I just wanted to make sure wether or not it was expected. I never use GM myself, but other users come complaining anyway, demanding that Wikipedia HTTPS-only is undone because 'it breaks their GM scripts'. Now I know what to tell them. "use the proper @grant's".

**Comment by arantius** [comment]
Said detection was added in 1.0, in 2012.  It was removed in 2.0, a year ago next week.

You're getting the standard very confused kind of report from your user.  Something else changed.  It is not related to HTTPS.  If you want to file a *bug report* please provide details, like (especially!) which script is in question?

If you want support, head to the [greasemonkey-users](http://groups.google.com/group/greasemonkey-users) support list.
