### ISSUE TITLE
GM_addStyle stops the script

### ISSUE THREAD

**Issue by SINE** [greasemonkey/greasemonkey#2302]
Sadly, for me Greasemonkey stops the script directly when GM_addStyle is being run, I'm guessing it will be some kind of bug.

Issue is happening to Firefox 41.0.2 on Windows. Tried it with both a fresh and an old profile.

##### The following script is an example of this behaviour, it will pop the first alert but not the second one, also the style is not being applied.
```
// ==UserScript==
// @name			test GM_addstyle
// @description		test
// @namespace		test-abc
// @match			*
// @version			1
// @grant all
// @noframes
// @run-at document-end
// ==/UserScript==

alert("before addstyle");
GM_addStyle("body{background:red;}");
alert("after addstyle");
```

Am I doing anything wrong?

**Comment by cletusc** [comment]
`all` is not a valid value for [@grant](http://wiki.greasespot.net/@grant). Open up your error console (`Ctrl+Shift+J` in Firefox) and it should show `GM_addStyle` is `undefined` which points to `@grant` being wrong somehow. See the [troubleshooting](http://wiki.greasespot.net/Troubleshooting_%28Users%29#Script_Errors) section of the wiki for some more info.

To fix this, instead of `@grant all`, use `@grant GM_addStyle`. If you need more GM APIs, just add another `@grant` line.

As this isn't really an issue with GM itself, it would have probably been better to post in the [greasemonkey-users](http://groups.google.com/group/greasemonkey-users) mailing list.

**Comment by SINE** [comment]
I have seen the @grant all in a script example that was selected as a solution on stackoverflow regarding some other topic, so I assumed it was valid without looking up the greasemonkey wiki.

Thank you very much for the info and sorry for the ticket.
