### ISSUE TITLE
How to use unsafeWindow on firefox43

### ISSUE THREAD

**Issue by mountainguan** [greasemonkey/greasemonkey#2382]
> // ==UserScript==
> // @name        NANA-Tool
> // @namespace    m-zhan.ml
> // @version      1.1 graduation final
> // @description  nana-tool
> // @match        http://nanabt.com/*
> // @domain       nanabt.com
> // @grant        unsafeWindow
> // @grant        GM_xmlhttpRequest
> // ==/UserScript==
> 
> var $ = window.$;
> //set window object
> var window = unsafeWindow;

Here are my codes,but it couldn't work on firefox43,the same code work fine on Chrome tampermonkey.What I want to do is to share the current web window object to my user script.

**Comment by janekptacijarabaci** [comment]
**Tampermonkey**
Throws an warning:
![1](https://cloud.githubusercontent.com/assets/2373486/14273316/06ec6dc6-fb0a-11e5-8cc0-d95408f5db1f.png)

**Greasemonkey**
Thus if you redefine the variable `window` => unsafeWindow...
Throws an error in the Browser Console:
![2](https://cloud.githubusercontent.com/assets/2373486/14273551/d6393176-fb0b-11e5-89c6-5af2b410783f.png)

IMHO: This error should be treated... (or to otherwise solve this issue? - see also https://bugzilla.mozilla.org/show_bug.cgi?id=1043958)

**Comment by mountainguan** [comment]
@janekptacijarabaci Without window object I couldn't achieve this.I redefine the window object so that my own functions can defined on GM script,and call in web page.

**Comment by janekptacijarabaci** [comment]
AFAIK, you can try this modification:

From:
`var window = unsafeWindow;`

To:
`window = unsafeWindow;`

**Comment by epicgirl1998** [comment]
do this

```javascript
(function(window){
	var $ = window.$;
	// script goes here
}(unsafeWindow));
```

**Comment by mountainguan** [comment]
@epicgirl1998 still not work…Chrome can directly support unsafeWindow,but Firefox seems work on a wired way…
