### ISSUE TITLE
Nightly can not parse match pattern

### ISSUE THREAD

**Issue by an-electric-sheep** [greasemonkey/greasemonkey#2480]
the script below fails with the following error: `Error: @match could not parse pattern`

```javascript
// ==UserScript==
// @name        match test
// @namespace   https://github.com/an-electric-sheep/
// @version     1
// @match       *://*.twitter.com/*
// @grant       none
// ==/UserScript==
```

It works on FF stable. I suspect that it would break a lot of scripts soon.

**Comment by janekptacijarabaci** [comment]
Last good: Firefox 54.0a1 (2017-02-09)
Built from https://hg.mozilla.org/mozilla-central/rev/b772e0f4138540113e91a46c99bb0d14ecc8acca

First bad: Firefox 54.0a1 (2017-02-10)
Built from https://hg.mozilla.org/mozilla-central/rev/25a94c1047e793ef096d8556fa3c26dd72bd37d7

Pushlog
http://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=b772e0f4138540113e91a46c99bb0d14ecc8acca&tochange=25a94c1047e793ef096d8556fa3c26dd72bd37d7

[Bug #1337629](https://bugzilla.mozilla.org/show_bug.cgi?id=1337629) is the suspect.

__Steps to reproduce__
1) Open Scratchpad
2) Menu: "Environment-Browser"
3) Insert the code:
``` javascript
var url = "http://*.twitter.com/*";
var ioService = Components.classes["@mozilla.org/network/io-service;1"]
    .getService(Components.interfaces.nsIIOService);
alert(ioService.newURI(url, null, null));
```
4) Run
5) The result:

__Firefox 54.0a1 (2017-02-09)__

alert: `http://*.twitter.com/*`

__Firefox 54.0a1 (2017-02-10)__
```
Exception: [Exception... "Component returned failure code: 0x804b000a
(NS_ERROR_MALFORMED_URI) [nsIIOService.newURI]"  nsresult: "0x804b000a
(NS_ERROR_MALFORMED_URI)"
location: "JS frame :: Scratchpad/1 :: <TOP_LEVEL> :: line 15"  data: no]
```

**Comment by valenting** [comment]
Hi, this looks to me like it is abusing URIs. Is there a specific reason why it's creating a URI using that pattern? How is it matching an actual URI vs a pattern URI.
Understanding this would help in deciding whether to backout bug 1337629 or not.

**Comment by an-electric-sheep** [comment]
@valenting it's using the URI to safely extract the various URI parts (scheme, host, path) before applying regular expressions to the individual parts. I assume the idea was to avoid implementing a custom URI parser for match patterns.

[MatchPattern.jsm](https://github.com/greasemonkey/greasemonkey/blob/3f462ac1305712ce65b3e2b19c9c8c31f377cc8e/modules/third-party/MatchPattern.js)

**Comment by an-electric-sheep** [comment]
Also note that for me this had the effect of silently removing or failing to load an already installed script. This was fairly surprising and I don't know if it would have been able to recover from that, i.e. if the script wasn't just gone until it is reinstalled.

**Comment by janekptacijarabaci** [comment]
The testing branch:
https://github.com/janekptacijarabaci/greasemonkey/tree/_testBranch_matchPattern

I did not make a pull request yet (it's not well tested)...

**Comment by DanaMW** [comment]
I had the same issue last night with Firefox developer. GM removed FBP script due to the two @match lines in his script with parsing errors. I removed the 2 lines and was able to load the script from disk to reinstall it.
GM was also missing a disabled script upon restart from the update of FF along with the purity script. The removed disabled one reloaded from clipboard without error. Neither script was removed from the gm_scripts folder thankfully, just wouldnt load. Hope any of this helps, here if you need me.
Parse error on these two;
// @match          http://*.facebook.com/*
// @match          https://*.facebook.com/*

**Comment by DanaMW** [comment]
Beta seems to be working fine.

**Comment by valenting** [comment]
Beta hasn't been updated yet. It will be soon.

**Comment by arantius** [comment]
I think arantius/greasemonkey@9cb94670994ea326e81ad6df4ec083d56e595166 fixes this.  Confirmation would be nice.

**Comment by arantius** [comment]
I rewrote that to arantius/greasemonkey@1531f342d512e9a0981897194bf3bf7ced09a1c7 and I'm pushing it out to the beta channel now.

**Comment by GuardianMajor** [comment]
I cannot confirm on the profile mentioned in #2481 because I had no choice but get it functional and had to scratch it and start over, a complete waste of hours. 

Not to mention in the process I find, that deleting/removing a script apparently doesn't actually remove/delete it, on the drive in the profile it keeps it all, which makes no sense why it is doing that - since I deleted these scripts for a reason, why are you collecting them?

Explains the errors that arise when a new script has the same name as an old one (deleted but not really gone) you didn't remove and causes issues. This should really be looked into, even though not directly related to issue being addressed here.
