### ISSUE TITLE
Allow to reload a script without reloading page

### ISSUE THREAD

**Issue by rdujardin** [greasemonkey/greasemonkey#2510]
Hi,

I was wondering if we couldn't add a button to reload a script without reloading page. I saw in issue #1469 that it was a bad idea to automate it, but this should be possible manually.

I'm working on a page which takes about 20-30 seconds to load each time and it's really painful.

People who would use this feature would be responsible to make their script able to reload during page lifetime, by avoiding irreversible actions or by calling first a reset function. I don't think this would be a problem.

We can even imagine a togglable default-deactivated automation on it... ?

What do you think ?
Thanks !

**Comment by lainverse** [comment]
It's might be possible to do, but script must provide unregister function which will undo everything script did on the page.
Since you'll have to write unregister code anyway then you can actually do update on your own too. This way you can place an update button anywhere on the page. Upload your main script in some other place like here on github and write script which will fetch() your code and run it. May require some tweaking to make sure it fetches script from a cache if it didn't change. I'd recommend to provide code as json with two functions: `{install:funciton(){...main code here...}, uninstall:function(){...uninstall code here...}}`

Then do something like this in GM script (haven't tested it, just an idea):
```
var myCode;
function downloadCode() {
    fetch(url)
    .then(resp=>resp.json())
    .then(function(json){
        myCode = json;
        if(myCode.install)
            myCode.install();
    })
    .catch(e=>console.log(e));
}
downloadCode();

function update(){
    myCode.uninstall();
    downloadCode();
}
```
