### ISSUE TITLE
Feature: disable console logging

### ISSUE THREAD

**Issue by arantius** [greasemonkey/greasemonkey#2516]
I'm working on my own user script, on a site for which I've got another script installed.  It's noisy to the console.  But I didn't write it, and I don't want to edit it (because I want updates to work).  If there was a per-script preference to mute the console logs coming from that script, I'd use it.

**Comment by arantius** [comment]
I've considered always muting console output by default, then enabling it when the script is edited.  Authors can debug to their heart's content.  Users aren't bothered.

The only caveat is if/when user script authors want to ask their users to read them console output, to figure out an issue.  What then?

**Comment by Eselce** [comment]
I would like to control console output of my scripts for **debugging AND production**. My scripts are written in a way, so that the complete output is needed (**controlled by my script**). If it's too noisy, I'd choose a different debug level **in my script**...

**Comment by arantius** [comment]
A) No need to "shout".
B) I know this, but the problem is that "too noisy" is very subjective and situational.  I suspect your use case is uncommon.  (And also, it's explicitly called out as my second paragraph...)

**Comment by Eselce** [comment]
No shouting intended, just emphasis.
Your second paragraph is my use case, as I need certain information for bug reports (or more often misusage by a user).
That's why I grouped my debug messages, the productive script will use much less output.

BTW: Which console do you mean (I'm confused with the new different console outputs).
I wouldn't like to float the Ctrl-Shift-J (browser?) console, but if someone uses Ctrl-Shift-K/Ctrl-Shift-I (web?) console, I wouldn't mind giving him all the information he needs (to get a clue or just tell me).

**Comment by arantius** [comment]
> ... if someone uses Ctrl-Shift-K ... console, I wouldn't mind giving him all the information he needs ...

That's exactly what I'm referring to.  When I'm developing my own scripts, I log there.  And in several cases I find it hard to read this console, because so much noise from other scripts shows up.

**Comment by Cerberus-tm** [comment]
By the way, another issue is this: what if something odd happens on a page, and a user wants to find out whether it's caused by some userscript's misbehaving. He could then first look at the console, to find out whether any userscripts are reporting issues, then disable or edit them. If userscripts only output things to the console while they're being edited, this becomes harder. Maybe this does not apply in most situations, but I think sometimes it does.
