### ISSUE TITLE
Using FF debugger with Greasemonkey Scripts

### ISSUE THREAD

**Issue by Sxderp** [greasemonkey/greasemonkey#2521]
Maybe I'm dumb?

I'm pretty sure that I used to be able to open up the Firefox Devtools that had a page with a userscript and step through the script using  the debugger. I could be imagining things though.. lol

Anyway, it seems that I can't do this anymore. Created a script, loaded the page, and it doesn't show up in the "sources" under the "debugger" tab. I haven't done any script writing in a while so I can't give much more specifics on when the problem appeared.

Small edit:
Using FF 54.0.1
Using GM 3.11

**Comment by mikhoul** [comment]
You can't see them with devtools you can see addon scripts but not GM scripts.

The best way to debug GM I've found is  send message to the console to see up to where your script run fine.

Regards :octocat:

**Comment by janekptacijarabaci** [comment]
Dupe fo #1844

**Comment by arantius** [comment]
I don't think this was ever possible.

**Comment by davispuh** [comment]
Why this is closed? I'm also looking for this feature and it seems that even now can't do this which is just stupid.

**Comment by Sxderp** [comment]
In the "WebExtension" world (2020) we can use the "userscript api". This allows for debugging using the Firefox tools. However Greasemonkey has not reworked the implementation to use this feature.

**Comment by lancerer314** [comment]
I guess there is a way to debug with the devtool because when there is an error in the userscript the debugger display the script code (augmented of GM object definition and other stuff) and from there i can add breakpoints.

This kind of give a workaround : add first a runtime error (if the js code is not well formed it looks like the script is just silently ignored) then add breakpoint, then fix the error, the breakpoint should still be there if you deleted or added lines.
