### ISSUE TITLE
4.x Add support for language translations

### ISSUE THREAD

**Issue by arantius** [greasemonkey/greasemonkey#2527]
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Internationalization

**Comment by arantius** [comment]
I have yet to find anything (though haven't looked much) like BabelZilla for web extensions.  I worry that translations are impractical without a tool like that to help.

**Comment by Sxderp** [comment]
I'm not sure I follow. I can't quite figure out what BabelZilla (as a tool/library/api, not the community) provides over the i18n provided in native WebExtension APIs.

Of course getting things translated is another matter. As that requires people. In which utilizing their interfaces and submitting the extension for translation is an avenue.

**Comment by arantius** [comment]
I'm referring to the latter.  A tool to help organize the volunteers, fill in partially-translated files, etc.  Everything its WTS did.

Especially: if we add a new string it could automatically copy the English version, so we don't have to do that by hand to make a new release.

**Comment by yfdyh000** [comment]
> Especially: if we add a new string it could automatically copy the English version, so we don't have to do that by hand to make a new release.

API does this, `"default_locale": "en"`.

https://www.transifex.com/, https://crowdin.com/, etc.

**Comment by arantius** [comment]
We're registered now:

https://www.transifex.com/--131/greasemonkey/

But I don't know how this site works yet; reach out to me if you'd like to contribute a translation.

**Comment by Eselce** [comment]
Dunno either. Signed up for german, using de or de_DE...

**Comment by Eselce** [comment]
Some issues (on transifex)...
First, my first activation mail timed out. Does it matter? Don't think so...
Tried to join, no immediate result. No access to the "team", not translators shown, maybe you have to take action(s)...
Is it `de` [German], `de_DE` [German (Germany)], or both?

**Comment by tobbexiv** [comment]
I use transifex for some other projects (and also requested to join for German).

There is a setting available that new requests to join a translation team will be automatically accepted. However, it seems to be set to off here. So, @arantius needs to accept every single new request.

There are also options to give more rights to other transifex members so they can help to accept new langauge requests / manage the team. This can also be restricted to only one language.

**Comment by Eselce** [comment]
That's what I've thought...

**Comment by Eselce** [comment]
@tobbexiv Is it just me, or doesn't anybody (else) have access to [Greasemonkey team](https://www.transifex.com/--131/teams/82856/)?

@arantius Please enable access, this is weekend here...

**Comment by arantius** [comment]
> I use transifex for some other projects (and also requested to join for German).
> 
> There is a setting available that new requests to join a translation team will be automatically accepted.

I can't find this.

> Please enable access, this is weekend here...

The only way I know how to do that is to click the "invite" button which requires an email address.

Also renamed so the link is now https://www.transifex.com/greasemonkey/teams/

**Comment by Eselce** [comment]
Got an acceptance mail...

**Comment by arantius** [comment]
> > There is a setting available that new requests to join a translation team will be automatically accepted.
>
> I can't find this.

Oh, found it!  Should have spent a few seconds more.  I think you might need to ask me to manually create languages though?

**Comment by Eselce** [comment]
>  I think you might need to ask me to manually create languages though?

Just performing that task now, not sure about the review part though (we'll see)...

**Comment by Eselce** [comment]
Hmm, where can I find these?
- Matches:
- $1 does not @grant method $2
- Does not run on:

@tobbexiv Please review `de` [German]

**Comment by Eselce** [comment]
Ah, found the first two of them now. It was a `HTML` file `src/content/install-dialog.html`

**Comment by Eselce** [comment]
Overview:
- [ ] English (en) [source language]  0% reviewed 100% translated 
- [ ] German (de)  0% reviewed 100% translated
- [ ] Chinese (China) zh_CN Requested by: yfdyh000
- [ ] German (Germany) de_DE Requested by: Eselce
- [ ] Japanese ja Requested by: 100の人 (so many? Giggle...)

Not sure about `lang` vs. fully qualified `lang_COUNTRY` codes...
Chinese may even distinguish between traditional and simplified!

**Comment by arantius** [comment]
I've just pushed 0552f5fbfc1221fef41fa59782f73ec0a60bac8f by downloading that file from transifex.  I've also seen language requests, and (requesting to) joining a language should be (approved) automatic.

I denied "de_DE" because we already have "de".  Please explain to me why we need both if you really want it.

**Comment by Sxderp** [comment]
> I denied "de_DE" because we already have "de". Please explain to me why we need both if you really want it.

Dialect differences? I don't know if it's much of a concern but that's a reason many places have `en_US` and `en_UK`.

**Comment by Eselce** [comment]
It's just a design (sometimes also practical) decision. I'd say, the only restriction is to be consistent.
These phrases are probably not so complicated, that you'll have to distinguish between e.g. swiss german and "german" german, although all over germany, there are quite a lot of local differences.
If you want to have a "fine line", you should provide language AND region (country).
For 35 phrases, this is probably not necessary. So I'm fine with just having `de` here as a sufficient setting.
(Another question is: Is the system able to choose `de`, if `de_DE` is set as language? Probably yes.)

`en_US` and `en_UK` are pretty usual though (funny, transifex uses `en_GB` instead of `en_UK`).

If you look at the requests (except from mine), there's `ja` (japanese) and `zh_CN` (chinese/mainland China).
And - as I mentioned - you may want to choose traditional chinese and simplified chinese, which are kind of very different. Mainland chinese may prefer simplified, while `hk` and `tw` usually use traditional chinese (or not?). When I think of japanese, there are also some different kinds of so called writings (and readings).
On another occasion, I've had some lengthy discussions with natives, and we've ended for the CJK languages with `zh` (simplified), `zh-tr` (traditional), `ja` and `ko`.

Actually, this made me look at Google translator, they use the same 4 categories...

**Comment by yfdyh000** [comment]
I think the `Enabled` and `Disabled` labels should change to `Disable` and `Enable`, as well as get a separate string key. In addition, `New user script ...` to `New user script...`.

**Comment by arantius** [comment]
> Regarding the language codes: How is the language determined?

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Internationalization#Localized_string_selection

**Comment by Eselce** [comment]
@tobbexiv Thanks a lot. I've checked most of the code locations and executed menus/dialogs/editor in order to decide, which phrases are best. That doesn't always mean word-by-word translation.
I can't really see, if you changed more than "Runs on:" and "Does not run on:" (do we need special "reviewers"?), I don't quite like any of our 4 translations each! It's the string on the installation dialog, followed by the @include and @exclude patterns respectively. That's why "Läuft auf:" etc. sounds quite silly. Same for "Matches:" for @match pattern, I'm not happy with that either...

Ah, found another (Anfrage/Abfrage)... Could be both for "request", that's okay...
Another (trust sources)... okay
Click Install... anklicken/wählen... The idea was, that Install(ieren) is selected (green), you can probably just type enter. But it's easy to convince me, that "click" is good enough...
Tab/Seite... I really don't like the Tab part. There's also a gender problem (diesen/dieses oder gar diese?). Scripts do operate on html pages within tabs or windows. Page sounds much better and is easier to comprehend!
aktiv/aktiviert and inaktiv/deaktiviert... A question of preference...

Looks like we have a common ground (there's only that tab stuff, that I really don't like)...
(and we should find a better solution for the @include, @exclude, @match patterns)
Is there no changelog overview? Had to go through all the phrases...
And there will probably be "0 reviewed" as long as there's no reviewer (not that this matters)...

This should work for us (use `de` only):

> 2. Otherwise, if the current locale is qualified with a region (e.g. en_US) and there is a messages.json file for the regionless version of that locale (e.g. en), and that file contains the string, return it.

**Comment by tobbexiv** [comment]
@Eselce 
Maybe we should move our discussion from here to transifex for discussions about specific translations. I created an issue comment with the Matches string so we can discuss the translation for match, include, exclude. I agree with you, that none of them sounds best. The comments are language specific, so we can also discuss in German. Might make the discussion easier.

Same me for Tab / Page discussion

> Click Install... anklicken/wählen... The idea was, that Install(ieren) is selected (green), you can probably just type enter. But it's easy to convince me, that "click" is good enough...
Other way around: You convinced me. Changed it back.

> aktiv/aktiviert and inaktiv/deaktiviert... A question of preference...
I thought this should be consistent and as it was deaktiviert in all places except one, I changed the one different place.

You can also filter for issues.

-------------

Reviewed strings cannot be changed anymore (except if you "unreview" it). Thus, it is possible to "freeze" translations using this functionality. So, I don't know whether it is necessary now. Might be good once we kind of finalized the translations. In other projects where I have the review option, I ponly review my own strings after several months so possible improvements can be made. So I would say this has time until arantius is more firm with transifex and how it works.

You can use different filters like "Translated before / after", "Translator", "Issue" ... by clicking on the search line above the list with translations / strings.

**Comment by Eselce** [comment]
ACK

Didn't know that about "review"...
Thanks for the filter hint!

**Comment by Eselce** [comment]
@yfdyh000 

> I think the `Enabled` and `Disabled` labels should change to `Disable` and `Enable`, as well as get a separate string key.

Are you sure about that? Remember, when you have an active script and click on that name,
you'll get the submenu with `(*) Enabled` selected. If you choose that item, the script will be
deactivated, showing `( ) Disabled`. `Disable`/`Enable` would describe the action to change the
status, not the status itself. I think, `Enabled`/`Disabled` is quite right, considering, that we also
use `Greasemonkey is active` and `Greasemonkey is disabled`...

> In addition, `New user script ...` to `New user script...`.

I would prefer that as well. That space looks weird for me...
(see **any** other Firefox menu that you have!)

**Comment by yfdyh000** [comment]
@Eselce Indeed, this seems to make sense that clicking the button will not close the pop-up menu, so describing its state itself (along with a checkbox) is acceptable.

**Comment by esperecyan** [comment]
@Eselce Thank you. I had mistakenly input the translation into not `message` property but `description`.

**Comment by Eselce** [comment]
> > Regarding the language codes: How is the language determined?
> 
> https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Internationalization#Localized_string_selection

I've tried to inspect all 4 versions, which lead to the surprising question:

How do I set the locale appropriately?

On the Settings page, I can choose a language, but it doesn't work (still german)!

(BTW: `zh_CN` is called `zh-cn` there)
