### ISSUE TITLE
Adopt an HTML templating tool

### ISSUE THREAD

**Issue by arantius** [greasemonkey/greasemonkey#2547]
I'm doing some HTML templating by hand at the moment and it's already a small mess.  Select a minimal tool for doing this more clealy, without adding too much bloat.

**Comment by arantius** [comment]
"Interesting" wrinkle; for a separate extension I just uploaded, review result was:

> This add-on is creating DOM nodes from HTML strings containing potentially unsanitized data, by assigning to innerHTML, jQuery.html, or through similar means. Aside from being inefficient, this is a major security risk. For more information, see https://developer.mozilla.org/en/XUL_School/DOM_Building_and_HTML_Insertion .

It's way off base, but this will rule out some/most templating tools.

**Comment by arantius** [comment]
https://preactjs.com/ ?

**Comment by arantius** [comment]
React/Preact require preprocessing/compilation style workflows I'd prefer to avoid.  Also looking at:

* https://github.com/hyperhype/hyperscript
* https://github.com/remy/bind.js
* http://rivetsjs.com/

But I'm generally not finding something I "like".

**Comment by Sxderp** [comment]
Wouldn't the preprocess / compile route provide performance benefit to the user? Rather than having to generate their documents through these abstraction frameworks they'd be served, relatively, static documents which have already been generated, no?

Of course this would make UI cycles a little more tedious. Though, at least with my own projects, once I've created the UI I don't often go back for major work. 

_Sent from my Motorola XT1095 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by eight04** [comment]
I think what @arantius meant is that React needs to compile JSX into regular JavaScript.

**Comment by arantius** [comment]
I ended up using rivets, the final link in my comment immediately above.  It's not perfect, but it is good (enough?) and small.  Requires managing repeated elements into arrays (where I'd prefer objects, at least some times), but the code to use it is concise and readable.
