### ISSUE TITLE
Switch to a proper Sandbox (Do not leak cross origin request abilities to all scripts)

### ISSUE THREAD

**Issue by arantius** [greasemonkey/greasemonkey#2549]
@tiansh [mentioned](https://github.com/greasemonkey/greasemonkey/issues/2484#issuecomment-318234857) that the current Greasemonkey/WebExt implementation accidentally grants its own cross-origin request abilities to every single script.

Address this somehow.

**Comment by arantius** [comment]
Like most properties of `window`, `fetch` and `XMLHttpRequest` cannot be mutated.

In theory I can `Proxy` away access to fetch, by passing a locally scoped `window`.  But then there's self and frames and content and top ... and what else do I not know about?  Leaving any one handle to the original fetch (or `XMLHttpRequest`) means the access is not prevented.

**Comment by jspenguin2017** [comment]
Do not execute untrusted code in content script scope. There will be bypass after bypass, and it'll be impossible to fix. Just look at Google's AngularJS sandbox, it is just not possible to create a reliable sandbox with just JavaScript.

**Comment by arantius** [comment]
As a webextension we have few options.  We can execute in content script scope, or web page scope.  Per my current understanding, for the latter:

* Content security policy will sometimes block user scripts. (Unless we break CSP?)
* Potential security holes are available to the entire world.

For the former:

* The user script will always run.
* Potential security holes are exposed only to the scripts you've installed.

I'm going for the "content" scope approach as the lesser of two evils.  Tracking https://bugzilla.mozilla.org/show_bug.cgi?id=1353468 to improve isolation, but expecting to launch without that (as I doubt that will be available for 57).

**Comment by arantius** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1332273 might also be related, depending on how it shakes out.

**Comment by arantius** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1353468 would address this

**Comment by CoolCmd** [comment]
I am very disappointed, because `@grant: none` does not work as before. This mode was designed to run a script with page privileges, like the other `<script>`'s on the page. I.e. user script must interact with page scripts without any strange things like `unsafeWindow`, `exportFunction`, etc. In GM4, part of the scripts with `@grant: none` will stop working. @arantius, in [this comment](https://github.com/greasemonkey/greasemonkey/issues/2549#issuecomment-329218545) you forget about 3rd important item: compatibility with GM3 and other script managers. Formerly, script authors could choose method of injecting scripts: sandboxed (xray) or plain. Now they can not. I understand why you switched to async API, but do not see much reason to break compatibility with the `@grant: none`.

**Comment by Sxderp** [comment]
> but do not see much reason to break compatibility with the @grant: none.

This is not completely intentional. Though, one potential, short-term, patch-up could be to wrap any `@grant none` script in `window.eval` (this can be done on the userscript side too) which _should_ run the script with the page context.

**Comment by CoolCmd** [comment]
@Sxderp 
> This is not completely intentional.

What a strange phrase :)

> window.eval

Yes, it works.  Anyway, `eval` is really evil. >:-E  And who will fix (turns to evil side) all "legacy" user scripts?

**Comment by arantius** [comment]
The current approach is a crappy compromise which I feel forced into.  I would *love* to be proven wrong, but as I understand it today, anything else will cause breakage as some pages' CSP settings would block any \<script\> tag injected or any `eval()` called.  (And I'm not going to defeat pages' intentional security settings as a work around.  I fear that's what TM/VM must be doing?)

(And yes, I know that thanks to Firefox bugs this partially happens anyway.  But that will be fixed upstream?)

**Comment by Sxderp** [comment]
> I fear that's what TM/VM must be doing?

I know that Violentmonkey uses `<script>` tags to execute the code. Assuming you can run your scripts on CSP pages then they must be circumventing it. _Unless_ the bug in which injected `<script>`  tags are not under CSP protection has been resolved[1].

[1]
Meta: https://bugzilla.mozilla.org/show_bug.cgi?id=1267027
Child 1: https://bugzilla.mozilla.org/show_bug.cgi?id=1406278
Child 2: https://bugzilla.mozilla.org/show_bug.cgi?id=1407056

Looks like it's resolved for 58?

**Comment by CoolCmd** [comment]
@arantius
> The current approach is a crappy compromise which I feel forced into.

I think you just piked the [wrong pill](https://github.com/greasemonkey/greasemonkey/issues/2549#issuecomment-329218545). :) I do not have statistics, but probably the sandbox now breaks much more user scripts than CSP. The CSP problem will soon be fixed in Firefox, because it affects many extensions. In contrast, the chances of fixing Firefox bug 1353468 are much less, because it affects only a few extensions. And even if Firefox implements sendbox, Chrome and Edge will not do it. As you know, market share of Firefox is relatively small. What kind of pill will the user script authors choose: create a compatible script that can run with the sandbox and without it (and which looks like a polymorphic virus), or order users to install the Tampermonkey extension, the behavior of which differs little in different browsers?

About CSP... One theory: other user script managers can modify CSP response header inside [webRequest handler](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webRequest).

**Comment by Sxderp** [comment]
> About CSP... One theory: other user script managers can modify CSP response header inside 

Yes, but then it's broken / removed for everything, not just your extension.

**Comment by Sxderp** [comment]
Also, this brings up another point. How do you provide access to privileged APIs with the `<script>` approach? In order to communicate with the extension you'd have use `window.postMessage` which is then open to the world, no?

**Comment by jspenguin2017** [comment]
No, you use `dispatchEvent`, with a secret event name.

**Comment by CoolCmd** [comment]
> How do you provide access to privileged APIs with the <script> approach?

[Here](https://github.com/greasemonkey/greasemonkey/issues/2549#issuecomment-346438997) I am talking about scripts that have `@grant: none`. Those scripts do not have privileged API.

**Comment by Sxderp** [comment]
I noticed you (@arantius) pinged the Bugzilla ticket. I don't have a Mozilla account so I'm going to post this here. 

I don't think obtaining the ability to directly create a Cu.sandbox will come again (I could be wrong). Might be better to put focus on a slightly different approach (which brings about roughly the same result). 

[Outlined here.](https://github.com/greasemonkey/greasemonkey/issues/2663#issuecomment-352267860)
