### ISSUE TITLE
Validate message sender

### ISSUE THREAD

**Issue by arantius** [greasemonkey/greasemonkey#2561]
The current codebase exposes `runtime.sendMessage()` to user scripts.  Dangerous things like the install/uninstall/list handlers are thus available.  When handling messages, always validate where they're coming from and service them only conditionally.

**Comment by Sxderp** [comment]
Would need to check the sender argument of each onMessage.
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/MessageSender

Slightly tangent, and doesn't really solve this particular problem: Would it be beneficial to use [ports](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/Port) for some of the message  passing in order to reduce, for lack of better term, the 'global' messaging space (since everything receives all standard messages..)?
