### ISSUE TITLE
matchPattern.doMatch is not a function

### ISSUE THREAD

**Issue by arantius** [greasemonkey/greasemonkey#2575]
10:13:23.525 matchPattern.doMatch is not a function 1 user-script-obj.js:30
	_testMatch moz-extension://.../src/user-script-obj.js:30:10
	runsAt moz-extension://.../src/user-script-obj.js:138:11
	scriptsToRunAt moz-extension://.../src/bg/user-script-registry.js:232:17
	...

Install 3.12, install a script which includes `@match`.  Install a 4.0alpha.  Load any page, get this error.

The match being saved (migrated in?) is the parsed MatchObject, not the string pattern, which is being handled incorrectly.

**Comment by Sxderp** [comment]
I think the problem is that when you [port.postMessage()](https://github.com/greasemonkey/greasemonkey/blob/202b6a66c93f908d5eb86cf5b4716d04ed3733c1/content/config.js#L467-L470). From looking at the documents, rather than doing some kind of clone of the objects, it seems like there is an internal [JSON serialization](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/Port). Therefore you lose your functions.

**Comment by arantius** [comment]
I should be sending the input string, not the parsed object.
