### ISSUE TITLE
IITC doesn't work with last Greasemonkey and Firefox Quantum

### ISSUE THREAD

**Issue by SignFinder** [greasemonkey/greasemonkey#2716]
Hi,
These scripts https://iitc.me/ don't work with last Greasemonkey and Firefox Quantum, but work with tampermonkey and FF Quantum.
Before updating to FF Quantum Greasemonkey+IITC was worked fine.
The IITC scripts change the appearance of the site https://www.ingress.com/intel

**Comment by Sxderp** [comment]
While it's great that you've let us known there's some incompatibilities, reports like this don't provide us with much help. It's unreasonable to expect us to open an 18 thousand line script and figure out what's wrong. Unless you can provide additional details, console logs (if there are any), minimal test cases, or otherwise point to some snippet then this is a non-starter.

**Comment by SignFinder** [comment]
Let me catch it.

**Comment by arantius** [comment]
Are you the author of IITC?  

If so, read: http://www.greasespot.net/2017/09/greasemonkey-4-for-script-authors.html
If not: this is expected.  Ask the author to fix it.

**Comment by SignFinder** [comment]
I am sorry for my misunderstanding, but if script works with tampermonkey+ff Quantum and worked with greasemonkey before FF was updated to FF quantum, why you suppose that the problem is in script.
I am going to provide the console logs for you, if it is necessary.
In any options - thank you very much, I will try to ask author of script.

**Comment by tobbexiv** [comment]
Greasemonkey 4.0 changed the API which is used by the script. This change is backwards incompatible as written in the announcement: https://www.greasespot.net/2017/09/greasemonkey-4-announcement.html

So, every script using one of these functions needs to adapt to this new API to continue working. As long as a script is not adapted, it will not work.
