### ISSUE TITLE
Remove ability to modify @requires content

### ISSUE THREAD

**Issue by Sxderp** [greasemonkey/greasemonkey#2717]
Firstly, I don't believe this was a feature of 3.x, or if it was I can't find a way to change anything in my FF 56 install. Secondly, it has been the cause of a bunch of problems, mostly to do with `@require` content not being available in scripts.

This may also lead being able to more easily streamline the editor / download / install / update script code paths. Right now they're all separate but I think they can be merged (in a rather simple manner). I have some ideas, one that I like but is contingent on detecting scripts in the background rather than in a content script. Probably post more info on the mailing list some time in the future.

**Comment by Eselce** [comment]
Really? That was a feature, that kept me "alive" while testing...

**Comment by arantius** [comment]
This absolutely was a feature of 3.x, because they were just files you
could edit.  Now without putting them in the embedded editor you can't
change them at all without re-installing the whole script.  Sometimes
you're developing it for the first time.  I consider it a critical feature
to be able to edit these in-place.

**Comment by darkred** [comment]
I totally agree with arantius: this is a very useful feature.
In fact, that't what help me fix the problem this problem https://github.com/pklauzinski/jscroll/issues/144,
which was to modify that jQuery plugin to use absolute paths instead of relative ones.
