### ISSUE TITLE
Add a GM.addStyle API, for styling CSP-restrictive pages

### ISSUE THREAD

**Issue by eradrix** [greasemonkey/greasemonkey#2724]
the current lack of scripting style is actually a complete disaster :-(

**Comment by CoolCmd** [comment]
addStyle is just few trivial lines of code. See [polyfill](https://greasemonkey.github.io/gm4-polyfill/gm4-polyfill.js).

**Comment by eradrix** [comment]
Thanks !

However that makes the current lack even more understandable...

**Comment by NoneGiven** [comment]
@arantius I've got an issue with trying to load user styles on pages which have CSP and don't allow "self" as an origin. GM could solve this with `[tabs.insertCSS()](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/insertCSS)`. Thoughts?

**Comment by Sxderp** [comment]
> I've got an issue with trying to load user styles on pages which have CSP and don't allow "self" as an origin -- so I can't just add a <style> element.

I think this will be hit in FF 58.

**Comment by NoneGiven** [comment]
I filed a [bug](https://forum.userstyles.org/discussion/61719/stylish-webextension-use-tabs-insertcss-instead-of-style-element) against Stylish since that's where I ran into the issue. Still, thought it might be worth considering here since GM's current APIs mostly expose privileged WebExt APIs that circumvent some content script restriction or other, and insertCSS is another one of those.

**Comment by NoneGiven** [comment]
Found the [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1267027) @Sxderp referred to (also [this one](https://bugzilla.mozilla.org/show_bug.cgi?id=1415352)). When those land, my suggestions here and on Stylish will be unnecessary.

**Comment by arantius** [comment]
I don't know exactly what "This should work if you bundle the CSS in your extension..." means, in the linked bug.  Dynamic node insertion might not work.

I'll reopen to consider CSP-safe functionality.  (But at a really low priority...)

**Comment by the8472** [comment]
In principle this could also be implemented without waiting for FF by passing up a message to the background script and running [tabs.insertCSS](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/insertCSS). But jumping through those hoops won't be necessary once that bug is implemented.

**Comment by NoneGiven** [comment]
@arantius [1415352](https://bugzilla.mozilla.org/show_bug.cgi?id=1415352) says "This should apply to both HTML `style` attributes and the contents of HTML <style> nodes."

**Comment by Arkanosis** [comment]
In case there's no plan to add a `GM.addStyle` (which is very fine for me if the CSP issue is addressed otherwise), I suggest to amend [this blog post](https://www.greasespot.net/2017/09/greasemonkey-4-for-script-authors.html) to make it clear that not only “As of today, there is no support for […] GM_addStyle”, but that none is planned in the future too (and maybe point to [this alternative](https://github.com/greasemonkey/gm4-polyfill/blob/master/gm4-polyfill.js#L33) as well). That might seems obvious, but it wasn't for me (had I not found this issue, I might be waiting for the feature to be re-implemented instead of fixing my scripts right now).

Thanks!

**Comment by trlkly** [comment]
Regarding the polyfill: ever since I heard that GM_addStyle was on the chopping block, I've actually only used 3 commands to replace it. Rather than testing for HEAD, I just add the STYLE directly to the documentElement, which is always present, even at document-start. 

    var style = document.createElement('style'); var style.textContent = `
    <Stylesheet here>
    `; document.documentElement.appendChild(style);

Here's the function version that I use more rarely, which clocks in at 5 lines:

    addStyle = function (css) {
      var style = document.createElement('style');
      style.textContent = css;
      document.documentElement.appendChild(style);
      return style; //optional, but convenient for changing the styling later.
    };

I've tested this in GM 3 and 4 on Firefox, and TamperMonkey on Chrome, without issue, despite not being standard. And I prefer nonstandard to having it fail if the HEAD has not yet loaded (which happens surprisingly often. I've had complaints.)

I also note that UserStyles,org uses my method as a fallback in its automatically generated userscripts.

**Comment by CoolCmd** [comment]
> Rather than testing for HEAD, I just add the STYLE directly to the documentElement, which is always present, even at document-start.
In FF57 and GM4, documentElement is **not** always available at document-start, at least on my machine.

**Comment by trlkly** [comment]
Since GM 4 (for now) has document-start happen even later than before, I'm
not sure how that's possible. But if the documentElement is not present,
then neither will be the HEAD element, since the documentElement is the
HTML element. which is what contains the HEAD element. So my method is not
any worse.

I admit I've not tested the latest dev on Fx 59, which uses a different
method to get document-start, but I hope the documentElement is present. If
not, then all sorts of scripts will break. You can't do anything to the
document before there is a documentElement. I don't even think you can set
up mutation observers.

I would definitely expect the document element to exist at the point when
any content script is injected.

**Comment by CoolCmd** [comment]
> I don't even think you can set up mutation observers.

You can attach mutation observer to `document`.
