### ISSUE TITLE
all scripts have stopped working

### ISSUE THREAD

**Issue by seasaltseasalt** [greasemonkey/greasemonkey#2769]
Greasemonkey updated automatically to 4.1  on my Firefox, and now all the scripts I have used have stopped working.

I have no idea where to start to resolve. I would prefer to go back but I dl 4.0 again and it did not override 4.1

What can I do as I am not a script writer. Thankyou

**Comment by Nulgar** [comment]
Even as a (private) script writer I'm confused why my script isn't working. Even a simple 
`window.addEventListener('DOMContentLoaded', function(){ [...]`
apparently doesn't work, but I get no errors in the console.

I can find **no** real info on what was changed beyond the [shift from GM_* to GM.* functions](https://www.greasespot.net/2017/09/greasemonkey-4-for-script-authors.html), nothing on whether accessing window/unsafeWindow was changed.

Also no info on that custom URL filters have been dropped completely, and existing ones forgotten, I had changed some after a website switched from http to https. At least that was somehow apparent from the reduced menu. Kinda ironic that an addon that's about customizing websites cuts down its own customization.

**Comment by Sxderp** [comment]
>  I would prefer to go back but I dl 4.0

You probably want 3.17

> Even as a (private) script writer I'm confused why my script isn't working.

The most likely problem is that the 'DOMContentLoaded' event is fired before the script is run. Now before  you come back and say `@run-at document-start` is set, that directive isn't fully supported at the moment. Due to the _very_ asynchronous nature of WebExtensions there's little guarantee on when something will be executed. When FF59 rolls around we'll have #2663 which will help. It'll actually help a lot of things, debugging too.

**Comment by talwrii** [comment]
I can confirm this on firefox-esr with vimperator.

```
firefox-esr --version 
Mozilla Firefox 52.5.0
```
