### ISSUE TITLE
GM4 backward compatibility Issue

### ISSUE THREAD

**Issue by erosman** [greasemonkey/greasemonkey#2776]
FF58 GM4.1

I am preparing a backward Polyfill for GM3 (a Polyfill to make scripts written for GM4 to work on GM3) but I get into errors.

```
console.log(typeof GM);  // object
console.log(typeof GM.openInTab);  // function
```

Next test ...

```
console.log(typeof GM);  // undefined

if (typeof GM === 'undefined111') {
  console.log('GM undefined called'); // no console log
  var GM = {
   // .. code
  };
}
```

Another test ...

```
console.log(typeof GM);  // undefined

if (typeof GM === 'undefined') {
  console.log('GM undefined called'); // GM undefined called
  var GM = {
   // .. code
  };
}
```

What am I missing here?!

**Comment by StigNygaard** [comment]
We should probably see the full script, but I think you are declaring GM without initializing it here:

```
if (typeof GM === 'undefined111') {
  console.log('GM undefined called'); // no console log
  **var GM = {**
   // .. code
  };
}

```
While the if-statement is false and GM is not initialized, it is still declared. How/why it overrides the Greasemonkey GM object (and if that is an error or not) I don't know.

Well, it is partly guessing. Posting complete script including userscript header might make it more clear.

**Comment by makyen** [comment]
The [existing polyfill](https://github.com/greasemonkey/gm4-polyfill) handles [this similarly](https://github.com/greasemonkey/gm4-polyfill/blob/master/gm4-polyfill.js#L27), but does not declare `GM`. It relies on the non-strict implicit creation of the `GM` property on the global object.

You can accomplish this in strict mode, but you have to explicitly operate on the global object's `GM`  property (e.g. `window.GM`), without declaring a `GM` variable with

    var GM =
If you do explicitly declare the variable with `var`, you will override the `GM` property which exists in Greasemonkey 4. This will prevent being able to access the `GM` object when executing within Greasemonkey 4, which is obviously not desirable for a polyfill.

The existing polyfill would probably be better if it was changed to be compatible with strict mode.

**Comment by erosman** [comment]
@makyen Thank you for the explanation.

The existing polyfill  is designed to make old GM3 scripts work with GM4, while I want a GM4 script to also work with older Firefox and GM3.

In other words, the code is written for GM4 with dotted object and I was working on a backward compatible so if GM object doesn't exist, create a GM object and assign the properties/functions to the old GM_** functions.

Why is `var GM =` evaluated when there is a conditional that should prevent it?

Working directly with global GM would complicate GM3 operation since there isn't such an object and the script would fail in strict mode (which I use 100% of the time).
Any suggestions?
I am going to see if I can reverse the Polyfill in a way that it workable.

> We should probably see the full script
Imagine that is the full script since the errors occurs there... I can make a dummy mini script if that is needed.

> While the if-statement is false and GM is not initialized, it is still declared. How/why it overrides the Greasemonkey GM object (and if that is an error or not) I don't know.
That is what got me confused as well.

> Actually you declare GM twice; In both if-statements. 
Where?! Those are separate test scripts

**Comment by StigNygaard** [comment]
> Why is var GM = evaluated when there is a conditional that should prevent it?

It is not evaluated. But declarations happens independently of that, and it doesn't matter where in the (same) scope the declarations are positioned. That's how Javascript designed. It is not specific for Greasemonkey.

> Where?! Those are separate test scripts.

Well, it was unclear to me. I thought it was multiple snippets of one big script.

**Comment by Eselce** [comment]
> The existing polyfill is designed to make old GM3 scripts work with GM4, while I want a GM4 script to also work with older Firefox and GM3.

If we are talking about `gm4-polyfill` (or the long name), this is **not**, what it does.
It may optionally (i.e. if not present) add some GM3 style functions under GM4, but not in general.

It **does** provide you the asynchronous GM4 interface (for GM4 style calls, i.e. GM4 scripts)
under GM3 or GM4 alike (using either full GM4 functionality or GM3 functions plus polyfilled GM3 functions).

> In other words, the code is written for GM4 with dotted object and I was working on a backward compatible so if GM object doesn't exist, create a GM object and assign the properties/functions to the old GM_** functions.

That is pretty much, what the polyfill does (under GM3: with async calls to GM3 functions)...

**Comment by erosman** [comment]
> That is pretty much, what the polyfill does (under GM3: with async calls to GM3 functions)...
Thank you @Eselce .. Let me have another look... I was under the impression it is made for GM3 script to work with GM4 and not the other way round.

**Comment by Eselce** [comment]
> I am preparing a backward Polyfill for GM3 (a Polyfill to make scripts written for GM4 to work on GM3) but I get into errors.

@erosman Hmm, I know, it's confusing. Strictly speaking, you said, that you wanted scripts written for GM4 (`GM.*` calls) work on GM3 (3.12 / 3.17). What it provides...

> I am trying to do the opposite. That is to map `GM` object to `GM_*` function

But I'm can imagine now, you wanted GM4 scripts (with GM.*) call GM3 functions on GM3 in a synchronous way (but why use `GM.*` calls?). I had a similar idea ("it's complicated"), and @StigNygaard as well. Check the library on GitHub that he wrote: https://github.com/StigNygaard/GMCommonAPI.js

On the other hand: If you are trying to **create** a `GM` object, you'll probably be trying `gm4-polyfill `stuff (but in `strict` mode).

**Comment by Eselce** [comment]
BTW @erosman This worked properly for me in `strict` and non-`strict` mode...
```
if (typeof GM == 'undefined') {
    var GM = {};
}
```

**Comment by makyen** [comment]
@Eselce Are you sure? While that doesn't produce an error, I've previously tried that. The result was that when running in GM4, the `GM` object supplied by Greasemonkey 4 gets overwritten. This causes all `GM.*` APIs to be unavailable in GM4. It works fine when running under GM3, or other userscript managers.

@erosman For strict mode, I would expect something like the following to be functional (untested):

    if (typeof GM === 'undefined') {
        window.GM = {};
    }

@erosman There appears to be some confusion as to what you are trying to do and/or what the [gm4-polyfill](https://github.com/greasemonkey/gm4-polyfill) does. The gm4-polyfill is specifically intended to be included using `require` in a script natively written for GM4 (async APIs), in order to permit the script to function when using GM3 (sync APIs) and all other userscript managers which implement the original GM API. It does this by wrapping the `GM_*` functions in a Promise and mapping them to `GM.*`.

It's not written for itself to operate in strict mode. While my opinion is that it should be written for use in strict mode, when included using `require` it doesn't normally need to be. However, if someone copies the polyfill text into a script which is `'use strict';`, then it won't work.

Frankly, my opinion is that the gm4-polyfill should be written such that it can work in strict mode, specifically so that users can copy it into their scripts which are using strict mode. Currently, there is *no actual testing* that occurs prior to code being merged into the gm4-polyfill. This has resulted in the polyfill being *completely* broken by a [merge the in the past](https://github.com/greasemonkey/gm4-polyfill/pull/4). Thus, I consider `require`ing the polyfill from it's main repository to be an unacceptable dependency for any script.

Personally, I solved this by making a copy of the polyfill script and `require`ing it from a location that I know has been tested prior to merging new code. However, a reasonable alternative is to copy the code into whatever script is going to use it, which also has the added benefits of removing an external dependency and having all code in one script (e.g. if someone was reviewing it from a security perspective). Thus, IMO, having it written to be functional in strict mode would be beneficial.

**Comment by erosman** [comment]
> This worked properly for me in strict and non-strict mode...

@Eselce What do you mean by working?

If you put that inside a GM4 script, it will overrides the GM global and that is precsisly the issue here.

Example:

```
if (typeof GM == 'undefined') {
    var GM = {};
}

GM.openInTab('http://www.google.com/'); // nothing happens here
```

**Comment by Eselce** [comment]
Hmm, I've tested that in the JS environment, assuming, that requirements are merely concatenated. But maybe that's a different thing in that environment than ultimately using @require...

Mixing `strict` and non-`strict` scripts (as one) is probably an issue (I mean the whole file, not just a function). That's why I agree, it would be preferable to be `strict`-compatible, but the whole script should not be strict (only if copied into another file).

**Comment by Eselce** [comment]
> Considerations:
> *   Code primary for GM4 (using GM object)
> *   Not 2 separate scripts, one for GM3 and one for GM4.
> *   Not reassigning new functions eg;
>     `let MyopenInTab = typeof GM === 'undefined' ? GM_openInTab : GM.openInTab;`
> *   Not having conditional every time an API is used (the real scripts has 100s of API usage) eg
>     `If (typeof GM === 'undefined') { GM_openInTab('http://www.google.com/'); }`
>     `else { GM.openInTab('http://www.google.com/'); }`
>
> Any ideas?

Please don't forget the `Promise` issue: `GM.*` will almost always return `Promise` objects under GM4, that's why `gm4-polyfill` contains (for a bunch of funtions)
```
GM[newKey] = function(...args) {
  return new Promise((resolve, reject) => {
    try {
      resolve(old.apply(this, args));
    } catch (e) {
      reject(e);
    }
  });
};
```
If you call GM3 functions directly (in a GM4 script, but with GM3 system), you will then fail to work with the returned `Promise`. Example:
```
GM.somefunction(arguments).then(res => console.log(res));
```
will fail with sth. like `GM.somefunction(...) is undefined`...

**Comment by Eselce** [comment]
BTW: One of these will probably not work in `strict` mode:

```
this.GM_addStyle = (aCss) => {
  ...
};
```
As well as the code above (`this` is not defined, it has to be assigned directly)...

**Comment by erosman** [comment]
> If you call GM3 functions directly (in a GM4 script, but with GM3 system), you will then fail to work with the returned Promise

That is more of concern for GM3 when running in GM4 not the other way round,. In any case, I write the code in such a way that it would work on both AFA promise is concerned.

The issue, and the point of this thread is to assign for example `GM.openInTab` to `GM_openInTab` if `GM object` is not present.

> BTW: One of these will probably not work in strict mode:

Again it seems you are converting GM3 to GM4 (like gm4-polyfill.js) while the intent is to convert GM4 to GM3

**Comment by Eselce** [comment]
This one is only added, if not existent (i.e. under GM4). So far, I agree...
```
this.GM_addStyle = (aCss) => {
  ...
};
```
But now that there **is** a `GM_addStyle` for GM 3 as well as for GM4, `GM.addStyle` is created as a `Promise` based function (if `GM.addStyle` doesn't already exist). In this case, the lines at the end of the file will be executed for BOTH systems (because there is no native `GM.addStyle` in GM4). But the aim is to create a `GM.*` function for (mostly) an existing GM3 interface (running under GM3, but with GM4 JS calls).

Don't be confused by the polyfills of functions, that do not exist as a native GM4 function (`addStyle`, `registerMenuCommand`, `getResourceText`). The most important operations are in the last few lines...

**Comment by makyen** [comment]
@erosman There appears to be a disparity in what we are calling things with respect to code written for GM4 and polyfilled into GM3 vs written for GM3 and polyfilled into GM4.

The gm4-polyfill is intended for you to be able to write your userscript using the GM4 APIs and have it function in GM4, GM3, and all other userscript managers. For instance, you could write code like (tested in both GM4 and GM3.17):

    // ==UserScript==
    // @name        Test GM polyfill being required
    // @namespace   gm4-polyfill-test
    // @description Very basic test of gm4-polyfill
    // @match       *://*/*
    // @version     1.0.0
    // @grant       GM.getValue
    // @grant       GM.setValue
    // @grant       GM_getValue
    // @grant       GM_setValue
    // @require     https://greasemonkey.github.io/gm4-polyfill/gm4-polyfill.js
    // ==/UserScript==
    'use strict';

    console.log('GM:', GM);

    let random = Math.random();
    console.log('random: ', random);

    GM.setValue('testValue', random).then(() => {
      GM.getValue('testValue').then(value => {
        console.log('value: ', value);
        console.log('value === random', value === random);
      });
    });

Perhaps some of the confusion is that in order to add *some* `GM.*` functions which are not actually provided by GM4, the gm4-polyfill first checks to see if they exist as `GM_*`. If the functions don't exist as `GM_*` it creates them (specifically `GM_addStyle`, `GM_registerMenuCommand`, and `GM_getResourceText`). However, it then assigns the `GM_*` functions to `GM.*` properties with:

    Object.entries({
      'GM_addStyle': 'addStyle',
      'GM_deleteValue': 'deleteValue',
      'GM_getResourceURL': 'getResourceUrl',
      'GM_getValue': 'getValue',
      'GM_listValues': 'listValues',
      'GM_notification': 'notification',
      'GM_openInTab': 'openInTab',
      'GM_registerMenuCommand': 'registerMenuCommand',
      'GM_setClipboard': 'setClipboard',
      'GM_setValue': 'setValue',
      'GM_xmlhttpRequest': 'xmlHttpRequest',
      'GM_getResourceText': 'getResourceText',
    }).forEach(([oldKey, newKey]) => {
      let old = this[oldKey];
      if (old && (typeof GM[newKey] == 'undefined')) {
        GM[newKey] = function(...args) {
          return new Promise((resolve, reject) => {
            try {
              resolve(old.apply(this, args));
            } catch (e) {
              reject(e);
            }
          });
        };
      }
    });

**Comment by erosman** [comment]
@makyen 
OK, lets see... 
What if we include `gm4-polyfill.js`?
I never use // @require

Including `gm4-polyfill.js` in the script content eg:

```
// ==UserScript==
// @name        Test GM polyfill being required
// @namespace   gm4-polyfill-test
// @description Very basic test of gm4-polyfill
// @match       *://*/*
// @version     1.0.0
// @grant       GM.getValue
// @grant       GM.setValue
// @grant       GM_getValue
// @grant       GM_setValue
// @require     https://greasemonkey.github.io/gm4-polyfill/gm4-polyfill.js
// ==/UserScript==
'use strict';

if (typeof GM == 'undefined') {
  GM = {};
}


if (typeof GM_addStyle == 'undefined') {
  this.GM_addStyle = (aCss) => {
    'use strict';
    let head = document.getElementsByTagName('head')[0];
    if (head) {
      let style = document.createElement('style');
      style.setAttribute('type', 'text/css');
      style.textContent = aCss;
      head.appendChild(style);
      return style;
    }
    return null;
  };
}

// the rest of gm4-polyfill.js



console.log('GM:', GM);

let random = Math.random();
console.log('random: ', random);

GM.setValue('testValue', random).then(() => {
  GM.getValue('testValue').then(value => {
    console.log('value: ', value);
    console.log('value === random', value === random);
  });
});
```

`@require` seems to be processed out of `'use strict';`, otherwise including the same code in above will fail.

**Comment by makyen** [comment]
@erosman I agree, the gm4-polyfill script should be written such that it can be copy-&-pasted like that into a `'use strict';` environment. I, also, am not a fan of adding an external dependency using `@require`.

I've changed the gm4-polyfill code such that it can be copy-&-pasted into a 'use strict'; script. I still need to do a round of testing under different browsers/userscript managers (so far only GM4/GM3). But, I'll see if I can submit a PR today.

**Comment by erosman** [comment]
@makyen That is exactly the issue here.

The conversion of new to old is trivial. However, that is dependant on declaring GM object and due to its global nature, the following fails in GM4 in 'use strict'.

```
if (typeof GM === 'undefined') {
  var GM = {};
}
```

**Comment by erosman** [comment]
Why was the topic closed?
Did someone post an answer somewhere?

**Comment by Eselce** [comment]
> @arantius Why was the topic closed?
> Did someone post an answer somewhere?

1. Strictly speaking, it's not a GM issue.
2. Answer: Yes, it doesn't work with `'use strict';`.
3. This is not a support forum.

You may add

4. Anyone with an idea may post a solution, even if closed.

**Comment by erosman** [comment]
> Strictly speaking, it's not a GM issue.
Maybe.. but then if not related to GM (and GM API) what is it related to? JavaScript?!
GM exist to provide support for user scripts.

> Answer: Yes, it doesn't work with 'use strict';.
Good answer should conform to good coding practise. 
Many add-ons have been rejected for JavaScript namespace pollution on AMO. 

> This is not a support forum.
Where should GM backward compatibly (with older versions of GM) be discussed?

> Anyone with an idea may post a solution, even if closed.
Sounds good.. but people wont be looking through closed topics, would they?

**Comment by Eselce** [comment]
> Using 'use strict' is plain good coding practise.

That's for sure. But if it can't work, this doesn't help you.

It was discussed, although there are better places (`gm4-polyfill`, `Greasemonkey` support forum, ...)

**Comment by makyen** [comment]
@erikvold I have opened [PR#10](https://github.com/greasemonkey/gm4-polyfill/pull/10) for the [gm4-polyfill](https://github.com/greasemonkey/gm4-polyfill) which works in both strict mode and non-strict mode. It works included with `@require`, or when copy-&-pasted into a script.

**Comment by erosman** [comment]
@makyen 
From what I can see, `global -> this -> window`
It basically created a temp variable for the window.

back to the original issue.....

I dont see where the code assigns for example `GM.openInTab` to `GM_openInTab`

The entire code reassigns OLD to NEW but I don't see anything that assigns NEW to OLD.

I got my code working with one of the methods I explained (that I was trying to avoid), but not with gm4-polyfill

**Comment by makyen** [comment]
@Eselce While this isn't, *very* strictly speaking, a GM issue, it *is* an issue with the gm4-polyfill. Given that GitHub issues have been *explicitly disabled* for the gm4-polyfill repository, the appropriate place for such issues is here.

As we all know, GM4 has changed multiple things which causes it to break a significant quantity of existing scripts, in addition to a having a significant loss of functionality and security compared to GM3. I'm not trying to blame anyone involved with GM development. IMO, the fault lies completely on Mozilla and their unrealistic time-frame for the cut-over to WebExtensions-only. It was crystal clear when the cut-over was first announced that WebExtensions *really* wouldn't be ready at the scheduled cut-over time and that there would be a significant amount of Firefox functionality which would not yet exist, let alone providing enough time for extension developers to change their extensions between the existence of such functionality and the cut-over.

But, we have to deal with the situation as it is, not as we'd like it to be. 

The change to using the GM-dot asynchronous APIs is the one that takes the most work from user script developers to be compatible (although the change to `@match` might affect more scripts). It is certainly in GM's interest to make it as easy for user script developers to be compatible across all user script managers and browsers. At one time, GM was the only game in town. That's no longer the case. It's now < 10% of the user script manager installed base. In it's current implementation, GM4.1, it provides significantly less functionality than is available from the alternatives.<sup>1</sup> GM can no longer just make changes and expect to drive the entire market in a particular direction without doing as much as possible to facilitate that change. Having a stable `gm4-polyfill.js`, which is tested and working in as many environments as possible and useable in as many ways as people desire is *very* beneficial.


Thus, to be brutally honest, this *is* a GM issue, because a gm4-polyfill that's as fully functional as possible makes it easier for user script developers to make their scripts compatible with GM4 without breaking compatibility with other user script managers. Basically, without gm4-polyfill it is *far* easier for user script developers to just decide that they aren't going to be compatible with GM4. Doing so doesn't cost them much installed base.

----

<sup>1. Sufficient such that, despite being a long term user of GM and *significantly* preferring GM (<4) over the alternatives for multiple reasons, most importantly security, I now recommend people switch to TM or VM. I look forward to the point when I can recommend GM4, but it's still in the recommend against category (if for no other reason than not being able to install from GitHub without using an about:config hack).</sup>

**Comment by makyen** [comment]
@erosman It assigns OLD to NEW, which is what's needed for user scripts written for the GM4 APIs to be functional when the script is loaded in an environment which supports the old APIs. The OLD interfaces are accessed by user script code though calls to the NEW interfaces.

You would only want to assign NEW to OLD if your script was intending to use the OLD interfaces in GM4, which only has the NEW (asynchronous) interfaces. This is significantly more complex, as the OLD interfaces are (mostly) all synchronous. A methodology would be need to be used to make the NEW interfaces appear to by synchronous.

The above has been the root of the confusion that has existed in this Issue. You've stated that what you want to do is write code that uses the NEW (asynchronous) interfaces, not the old interfaces. However, you've also stated that you want to assign the NEW interfaces to OLD, which is the *opposite* of what's needed in order to have code that calls `GM.openInTab()`.

So, one way or the other, we're still not communicating. Do you want to have your code call `GM.openInTab()` or have it call `GM_openInTab()`?

If you want to write code that makes calls to `GM.openInTab()`, then the gm4-polyfill does that.

If you want to write code that makes calls to `GM_openInTab()`, then the gm4-polyfill does NOT do that, and has never been intended to do that.

**Comment by makyen** [comment]
@erosman `global` is not the same as `window` in any of the user script managers I checked. In GM, the GM APIs exist as properties of `global`. In TM and VM the GM APIs exist as properties of `window`.

**Comment by Eselce** [comment]
@makyen Okay, that `global` is a solution for that matter...

> @Eselce While this isn't, very strictly speaking, a GM issue, it is an issue with the gm4-polyfill. Given that GitHub issues have been explicitly disabled for the gm4-polyfill repository, the appropriate place for such issues is here.

Yep, `gm4-polyfill` would be the place, but as you said, issues were deactivated. Forgot about that!

**Comment by Eselce** [comment]
> not being able to install from GitHub without using an about:config hack

@makyen I'm avoiding that hack, if I can. Okay, you can't use `Raw`, but you can still use the `github.io` stuff, can't you? Or other solutions. And remember that `file:` PullRequest #2780...

**Comment by Eselce** [comment]
@erosman I agree with @makyen, and maybe you should provide a short GM script, that should work (under `GM` x.y with browser abc), then we can show you, that/how it works properly...

**Comment by Sxderp** [comment]
Because I want to contribute to a dead horse.

> PS3. Off-Topic: Is the global GM in GM4 accessible/exploitable by page scripts?!!

No.
1. It's not really going to contain much because `GM_*` functions don't exist in GM4. So it'll only contain the very specifically defined functions in the polyfill.
2. GM4 runs user scripts as a content script. Any objects created in the content script are not accessible by the page. The page will spit an 'access denied' error or some-such.

**Comment by erosman** [comment]
@makyen 
Maybe it was not clear. I have tried to make it clearer a few times.

- I have users that use my scripts.
- I want to write the code in the style of the new GM4
- Some users have upgraded to FF57 & GM4
- Some users, have decided NOT to upgrade to FF57 and remain with older FF, or using ESR or other Mozilla based browsers; and use GM3 (3.11)

Imagine a simple code written for GM4 (as already given)

    // ==UserScript==
    // @name SomeScript
    // @include https://www.example.com/*
    // @grant GM.openInTab
    // @author erosman
    // @Version 2.0
    // ==/UserScript==

    (() => {
    'use strict';

      GM.openInTab('http://www.google.com/');

    })();


The above code works fine in GM4 but doesn't work in GM3

One can make 2 versions of the code, one for GM4 (above) and one for GM3 (below), but that is undesirable.

    // ==UserScript==
    // @name SomeScript
    // @include https://www.example.com/*
    // @grant GM_openInTab
    // @author erosman
    // @Version 2.0
    // ==/UserScript==

    (() => {
    'use strict';

      GM_openInTab('http://www.google.com/');

    })();

Currently, I have solved this issue by:

    // ==UserScript==
    // @name SomeScript
    // @include https://www.example.com/*
    // @grant GM_openInTab
    // @grant GM.openInTab
    // @author erosman
    // @Version 2.0
    // ==/UserScript==

    (() => {
    'use strict';

      (typeof GM_openInTab === 'undefined' ? GM.openInTab : GM_openInTab)('http://www.google.com/');

    })();

Above works in both GM3 and GM4, but I was looking for a more robust option.

As already mentioned, `gm4-polyfill` provides a method to convert OLD functions to NEW while I am trying to convert NEW to OLD, when needed.

In other words, a code written for GM3 can be used in GM4 by using `gm4-polyfill` (regardless of the strict issue).

However, a code written for GM4 can NOT be used in GM3 and `gm4-polyfill` provides no method to achieve it.

The issue has never been about `gm4-polyfill`. In fact it is about a `gm3-polyfill` type code (if existed) with the option to recognise both GM3 & GM4 functions.

**Comment by StigNygaard** [comment]
Okay, I left this discussion because I found it highly confusing. I kind os till do. But you want this code written for GM4

```
// ==UserScript==
// @name SomeScript
// @include https://www.example.com/*
// @grant GM.openInTab
// ==/UserScript==
(() => {
'use strict';
  GM.openInTab('http://www.google.com/');
})();

```

to run in not only in GM4, but also in GM3 (and maybe also Tampermonkey etc.)?
Well, that's exactly what gm4-polyfill is designed for...

**Comment by erosman** [comment]
```
Okay, I left this discussion because I found it highly confusing. I kind os till do. But you want this code written for GM4
...
to run in not only in GM4, but also in GM3 (and maybe also Tampermonkey etc.)?
```
Exactly

> Well, that's exactly what gm4-polyfill is designed for...
No it is not. `gm4-polyfill` is designed for the **code written for GM3** to also work in both GM3 & GM4 (not the other way round)

**Comment by tobbexiv** [comment]
> No it is not. `gm4-polyfill` is designed for the code written for GM3 to work in both GM3 & GM4, not the other way round which is code written for GM4 to work in both GM3 & GM4

No. The polyfill makes it possible to use scripts written for the new GM4 API also in addons that do only support the old api. It is impossible to make a polyfill that makes it possible to still use the old api. You will always have to adopt to the new api, as the async calls from the new api cannot be used in a synchronous way (which is the old api).

Thus, if you write your code in a way that works in the GM4 api, you can simply include the polyfill and it should also work in any userscript manager for the old api. The other way around is not possible.

**Comment by erosman** [comment]
> Thus, if you write your code in a way that works in the GM4 api, you can simply include the polyfill and it should also work in any userscript manager for the old api. 

Which polyfill? gm4-polyfill?
`gm4-polyfill` does not make the code written for GM4 work in GM3 environment. it works the other way round, as previously stated multiple times.

> You will always have to adopt to the new api, as the async calls from the new api cannot be used in a synchronous way (which is the old api).

Code can be written (I have) in such a way that the async execution would work in both GM4 & GM3. That is not the issue, as previously stated. The issue is the API.

**Comment by StigNygaard** [comment]
@erosman , I'm afraid you have totally misunderstood the purpose of gm4-polyfill.

The following code should work in GM4, GM3, Tampermonkey and Violentmonkey:

```
// ==UserScript==
// @name polytest
// @include https://github.com/greasemonkey/greasemonkey/issues/*
// @require https://greasemonkey.github.io/gm4-polyfill/gm4-polyfill.js
// @grant GM.openInTab
// @grant GM_openInTab
// ==/UserScript==
(() => {
  'use strict';
  GM.openInTab('http://www.google.com/');
})();
```

I have verified it is working with Firefox/GM4, Chrome/Tampermonkey and Opera/Violentmonkey.

Remember to grant both GM.openInTab and GM_openInTab, since the later is used behind the scene.

gm4-polyfill makes the GM4 API available in GM3, Tampermonkey and Violentmonkey.

**Comment by erosman** [comment]
> I have verified it is working with Firefox/GM4, Chrome/Tampermonkey and Opera/Violentmonkey.
That is correct. It works in both GM4 and GM3 by creating a global GM and rewriting any old GM_* functions as GM.*

So far so good.

The problem (besides the undesired `@require` ) is that current  `gm4-polyfill.js` only works in that way and as a script not compatible with 'use strict'. As it is, it is not possible to include the code snippet within a script.

**Comment by Sxderp** [comment]
Why is `@require` undesired? Why copy and paste the same code into every script? What ever happened to "reduce code duplication?" It's not like the file is redownloaded every time it is run. The `@require` is downloaded once and then stored on your machine. Not to be fetched again. If you're concerned about the file changing then just link off of a specific commit rather than master. 

I don't see the problem here. You're intentionally making this difficult for little benefit.

**Comment by Sxderp** [comment]
Further more, if you wish to modify the contents, you can switch to the specific tab in the editor.

**Comment by erosman** [comment]
> Why is @require undesired? Why copy and paste the same code into every script? What ever happened to "reduce code duplication?" 

I have my reasons which goes beyond the scope of this already long discussion. 

> It's not like the file is redownloaded every time it is run. 
True.. but it is downloaded once for every script, doesn't it?

> I don't see the problem here. You're intentionally making this difficult for little benefit.
Intentionally no... but that could be the case unintentionally.

I started by wrriting my own code snnipet (hence the startin of this topic)

An example ...

```
if (typeof GM === 'undefined') {
  var GM = {
    'addStyle':             (...a) => GM_addStyle(...a),
    'deleteValue':          (...a) => GM_deleteValue(...a),
    'getResourceUrl':       (...a) => GM_getResourceURL(...a),
    'getValue':             (...a) => GM_getValue(...a),
    'listValues':           (...a) => GM_listValues(...a),
    'notification':         (...a) => GM_notification(...a),
    'openInTab':            (...a) => GM_openInTab(...a),
    'registerMenuCommand':  (...a) => GM_registerMenuCommand(...a),
    'setClipboard':         (...a) => GM_setClipboard(...a),
    'setValue':             (...a) => GM_setValue(...a),
    'xmlHttpRequest':       (...a) => GM_xmlhttpRequest(...a)
  };
}
```
Note: `gm4-polyfill.js` assigns all to the global GM and I was trying to assign GM to old functions without making it global.


Then I run into trouble on GM4 with `var GM = `
That is when I posted this topic.

`gm4-polyfill.js` achieves this by breaking the `'use strict'`. I wanted to do it without breaking  `'use strict'`

Then we got sides-tracked into all sorts of issues and the topic became confusing.

**Comment by eight04** [comment]
Just use another name to avoid the conflict:
```js
var MyGM;
if (typeof GM === 'undefined') {
  MyGM = {
    'addStyle':             (...a) => GM_addStyle(...a),
    'deleteValue':          (...a) => GM_deleteValue(...a),
    'getResourceUrl':       (...a) => GM_getResourceURL(...a),
    'getValue':             (...a) => GM_getValue(...a),
    'listValues':           (...a) => GM_listValues(...a),
    'notification':         (...a) => GM_notification(...a),
    'openInTab':            (...a) => GM_openInTab(...a),
    'registerMenuCommand':  (...a) => GM_registerMenuCommand(...a),
    'setClipboard':         (...a) => GM_setClipboard(...a),
    'setValue':             (...a) => GM_setValue(...a),
    'xmlHttpRequest':       (...a) => GM_xmlhttpRequest(...a)
  };
} else {
  MyGM = GM;
}

MyGM.openInTab(...)
```

**Comment by Sxderp** [comment]
> True.. but it is downloaded once for every script, doesn't it?

Sure, but that's no different than manually including the code in every script. Same amount of data needs to be downloaded. But instead of one network connection (to the source provider) you need two (to the source provider and the require provider). 

If you're worried about external `@require` (that you have no control over), then just fork the polyfill and link it from your own GitHub repo. That way if you make changes you just need to update the commit the link is pointing too. 

--- 

If I could I would turn off comments for this thread and open a new one asking to make the polyfill `'use strict;'` compatible. 

In the meantime potential workarounds have been suggested. A fix was attempted earlier in the thread (but didn't work as I pointed out in the corresponding Pull Request). 

If anyone has any further _useful_ information then go post a Pull Request or a specific issue. I think all has been said.

**Comment by erosman** [comment]
> Just use another name to avoid the conflict:
That was a possibly that I considered. I was hoping to stay close to the GreaseMonkey API.

> If I could I would turn off comments for this thread and open a new one asking to make the polyfill 'use strict;' compatible.

That is a good option... however, this thread was not about the existing `gm4-polyfill.js` at all.

**I wanted to see how I can refine GM object without getting into errors.** 

My scripts do not use all of the GM APIs. In fact I have re-written all of them not to use the obsolete APIs (eg. GM_addStyle, GM_registerMenuCommand, etc).
In case of those that are used, I wanted to include a couple of lines of code to make them compatible with GM3, which I still can, but was looking for a more robust approach.

One script for example, only uses `GM.openInTab` and that can be fixed with 1 line of code without the need to `@require` anything.

Then `gm4-polyfill.js` was suggested and we got deeply into `gm4-polyfill.js` discussion.

**Comment by eight04** [comment]
> I wanted to see how I can redefine GM object without getting into errors.

If `GM` object is defined in an outer scope, you can't. The variable is [shadowed](https://eslint.org/docs/rules/no-shadow) by the local variable (which is defined in your script). If you really want to use that variable name without losing access to the outer variable, you can create another scope:
```js
var MyGM;
if (typeof GM === 'undefined') {
  MyGM = {...};
} else {
  MyGM = GM;
}
{
  const GM = MyGM;
  GM.openInTab(...);
}
```
Or use IIFE:
```js
function getGM() {
  if (typeof GM !== "undefined") {
    return GM;
  }
  return {...};
}

(GM => {
  GM.openInTab(...);
})(getGM());
```

----

BTW, I think current code of [gm4-polyfill](https://github.com/greasemonkey/gm4-polyfill/blob/e6f01bf925a272a9563ff9b652b894bbd668e735/gm4-polyfill.js#L28) may [leak the API to page script](https://github.com/Tampermonkey/tampermonkey/issues/362) in Tampermonkey. Maybe @derjanb would like to see this.

**Comment by derjanb** [comment]
@eight04 Thanks for the hint. Yes the current polyfill will leak the GM object to page scripts at the current stable version. TM beta already supports the GM-dot API and therefore this is not an issue there if at least one GM.function is requested via `@grant`. The current plan is to release a new stable version soon if no other issue appears.

**Comment by erosman** [comment]
@eight04 Thank you for the suggestions.
