### ISSUE TITLE
Minor notification/port issue

### ISSUE THREAD

**Issue by Eselce** [greasemonkey/greasemonkey#2848]
During some of my tests, I got some console messages from e.g. `shoelace.css`, `font-awesome.min.css` and `codemirror.css`, but more interesting, there was an unsynced port/channel. Pretty much every notification window close produced:
```
port is undefined  on-user-script-notification.js:50
```
and only once, I got (same line):
```
Attempt to postMessage on disconnected port  on-user-script-notification.js:50
```
The source code was:
```
47: chrome.notifications.onClosed.addListener(id => {
48:   let port = portMap.get(id);
49:   portMap.delete(id);
50:   port.postMessage({type: 'ondone'});
51:   port.disconnect();
52: });
```
I didn't really analyze it yet, but here I use Win 8.1, FF 59.0b9 (64 Bit), GM 4.3beta4...

**Comment by Sxderp** [comment]
The first error is easily fixable. The notification handlers are global and therefore are triggered for every notification. The notifications you were receiving were not created with an associated port (used for user scripts). Therefore undefined ports. Fix by doing `if (port) { ... }` for the `onClicked` and `onClosed` listeners in that file.

As for the second error, I dunno. Do you have a script with the `GM.notification` permission? I don't see how the `portMap` would have any ports in it otherwise.

**Comment by Eselce** [comment]
> Do you have a script with the GM.notification permission?

A) Yes.

```
// ==UserScript==
// @name     i18n test
// @version  1
// @grant    GM.notification
// ==/UserScript==

try {
	GM.notification("Mein Text");
} catch (exception) {
	alert(exception);
}
```
B) Yes, but no: I've tested to create a new script and rename it to an existing name (`i18n test`).
This produced an error notification (first issue with port). The error is probably due to the script above.
