### ISSUE TITLE
Install panel is broken in 4.3beta5

### ISSUE THREAD

**Issue by quilloss** [greasemonkey/greasemonkey#2865]
Browser Console:
`ReferenceError: SUPPORTED_APIS is not defined parse-user-script.js:87:1`

I think `install-dialog.html` is missing `supported-apis.js`.

**Comment by arantius** [comment]
Note: iff you try to install something that does any `@grant` other than `none`. (Confirmed.)

**Comment by Eselce** [comment]
I did - but I got no answer... Forget to report the error message though... ;-.(

**Comment by Eselce** [comment]
Repaired? Asking for a friend...

**Comment by arantius** [comment]
> I did - but I got no answer

FYI I suspect you're misunderstanding what [iff](https://en.wikipedia.org/wiki/If_and_only_if) means.  (I was saying, above, both that I've confirmed the issue but also that it happens if and only if the script being installed `@grant`s a special API.)

**Comment by Eselce** [comment]
I know exactly, what `iff` means. I understood your post. What I was telling you, was, that I asked long before the release, if the current version (with your massive redesign) was supposed to work, because it didn't. I got no answer, but later, these (unchanged) version was used to create `4.3beta5`. You may say, you don't need install of scripts with `@grant` working, but I can't recommend the users of my scripts using this buggy version. Although it was avoidable...

**Comment by arantius** [comment]
Of course it was supposed to work, one line got missed by mistake.

**Comment by Eselce** [comment]
`4.3beta6` shows me an install dialog again. Works!
