### ISSUE TITLE
Please display current version in the install dialog, if already installed

### ISSUE THREAD

**Issue by zuckel** [greasemonkey/greasemonkey#2877]
The install dialog currently gives no indication whether the user is installing a new script or updating an existing one. Please consider showing the currently installed version in case an existing script is going to be overwritten.

**Comment by arantius** [comment]
A good UI mockup would make it easier to proceed.  I'm not sure I know how I'd want it to look.

**Comment by Sxderp** [comment]
`oldversion` -> `newversion`

**Comment by zuckel** [comment]
I'm with @Sxderp here. Simple does it.

Additionally I would, in case of an update, change the text on the install button to make the distinction clearer. If no version of the script is currently installed, it should still say `Install`. But if some existing version is going to be replaced, it should say something else, e.g. `Update`.

**Comment by zuckel** [comment]
I'm looking into the code right now to see if I can create a pull request, but I am unfamiliar with the technologies used. Currently I am puzzled by two simple things:
- How do the properties like `version` find their way into `install-dialog.html`?
- What would be the correct way to make the text change? It seems that i18n happens late, so I would guess I would have to use a branch directly in `install-dialog.html`.

**Comment by zuckel** [comment]
Alright, I've found my way around a little. Not sure when I find the time to really dig into this though. It seems the biggest change would to be getting the previous version of the script as the database is currently not consulted at all.

**Comment by zuckel** [comment]
So, I've played around a little and I actually arrived at a minimal working product. It's ugly but I'm glad I got it working. Leaving this here for now as I'm heading away from my computer for today.

- Is it necessary to add translations for all known locales?
- Is `gDetails` actually necessary? It seems like a relict to me.
- The new Promise can certainly be cleaned up, though I don't know how.
- No idea if error handling is working/sufficient or not.
- Currently iterating over all installed scripts. A direct id lookup could be provided by the registry instead.
- There is no `id` getter on `scriptDetails`, therefore I am comparing `namespace` and `name` individually. There are probably some cases that are handled incorrectly here.

**Comment by Sxderp** [comment]
> Is it necessary to add translations for all known locales?

No, just add English. Third-parties will help us with the rest.

> Is `gDetails` actually necessary? It seems like a relict to me.

I don't think so. But make a separate PR to fix this, rather than bundling it in yours.

> The new Promise can certainly be cleaned up, though I don't know how.

I haven't looked at the code in a while, but is there a Message to retrieve a single script? If not, it might be worth utilizing the 'getScriptById' code bits (about line 75 in the registry, create a new function for it) and creating a new Message, rather than doing the filtering in the content-script.

> No idea if error handling is working/sufficient or not.

Since all errors were expected to happen in the Downloader (anything else would have just been syntax errors) that particular promise chain does not have a `.catch`. It may not be necessary, perhaps depending on how / if you rework the Message I talked about above. The `.catch` would probably go on the Promise directly, rather than on the chain (or as the direct next link in the chain), so that you'll catch the errors above and then be able to pass `scriptDetails` to the rest of the chain. Not sure if any of that made sense.

> Currently iterating over all installed scripts. A direct id lookup could be provided by the registry instead.

Since I was going through the list items one at a time. This has already been covered.

> There is no `id` getter on `scriptDetails`, therefore I am comparing `namespace` and `name` individually. There are probably some cases that are handled incorrectly here.

Somewhat related to what I said above, if you reuse the 'getScriptById' code bits you can leverage existing methodology.

**Comment by zuckel** [comment]
I don't have time to polish my PR into the desired state. Current impl works for me.
