### ISSUE TITLE
Install fail

### ISSUE THREAD

**Issue by arantius** [greasemonkey/greasemonkey#2901]
GM 2018.03.09nightly, trying to install https://github.com/greasemonkey/greasemonkey/blob/master/test/scripts/many-include-exclude.user.js .  Dialog shows a raw rivets template error, console shows:

    Installer could not get script details: Error: Could not parse, no meta.

**Comment by arantius** [comment]
Same behavior (different logged error) at https://github.com/greasemonkey/greasemonkey/blob/master/test/scripts/match-invalid.user.js .

**Comment by Sxderp** [comment]
For the second issue, should it even install? You end up installing a broken script. Broken in a potentially harmful manner. Rather than matching, taking the example script, just localhost you end up running the script on everything.

An alternative would be to do something like TM does (assuming it still does this). Install the script but do not match on anything. Or force install disabled for review.

**Comment by arantius** [comment]
It shouldn't install, but it also shouldn't have (e.g.) a button labeled literally `{'cancel'|i18n}`.

**Comment by Sxderp** [comment]
> It shouldn't install ...

Might be a good idea to include that in the description of the script.

**Comment by Sxderp** [comment]
The first issue is due to `user-script-parse#parseUserScript` [throwing on missing meta](https://github.com/greasemonkey/greasemonkey/commit/74bcfce5be8d9cf7a40eba9ce88b19a2f3952d0e#diff-7e16c9ca62306c9c67675d942dfb25e1R61). The downloader doesn't catch this, rather it expects a returned falsy value. Considering failing to find the metadata should be non-fatal, an error should not be thrown. The behavior of the old `parseUserScript` was to just return `null`.

The second error is partially related. But I think it should be split into a different issue.

**Comment by Sxderp** [comment]
see #2902 for splitting the issue

**Comment by arantius** [comment]
You say "The downloader doesn't catch this, rather it expects a returned falsy value."

Then what's this https://github.com/greasemonkey/greasemonkey/blob/9010507b6e0ac52ec89bdba87521af3333189b4a/src/downloader.js#L202 ?
