### ISSUE TITLE
Check whether VM and/or TM backups can be imported

### ISSUE THREAD

**Issue by Sxderp** [greasemonkey/greasemonkey#2922]
[This is more of a TODO rather than an issue]

Importing from VM or TM backup should be supported. Although different levels of support.

- TM
-- Should be able to import scripts + associated value store data.

- VM
-- Should be able to import scripts.

**Comment by arantius** [comment]
Ideally there would be a `.zip` from each (with one same script and settings?), and automated testing of the import.

**Comment by arantius** [comment]
Repeat the above but with 
https://gist.github.com/arantius/1417946#file-with-one-resource-user-js
and
https://gist.github.com/arantius/1417946#file-with-one-require-user-js

Then all of the above again, skipping Greasemonkey, from Chrome.  Result:

    $ ls -o *.zip
    -rw-r--r-- 1 arantius  3487 May  2 10:36 require-from-gm-fx.zip
    -rw-r----- 1 arantius  1103 May  2 10:48 require-from-tm-cr.zip
    -rw-r--r-- 1 arantius  1103 May  2 10:34 require-from-tm-fx.zip
    -rw-r----- 1 arantius   861 May  2 10:45 require-from-vm-cr.zip
    -rw-r--r-- 1 arantius   837 May  2 10:32 require-from-vm-fx.zip
    -rw-r--r-- 1 arantius  2792 May  2 10:38 resource-from-gm-fx.zip
    -rw-r----- 1 arantius  1112 May  2 10:48 resource-from-tm-cr.zip
    -rw-r--r-- 1 arantius  1111 May  2 10:35 resource-from-tm-fx.zip
    -rw-r----- 1 arantius   864 May  2 10:46 resource-from-vm-cr.zip
    -rw-r--r-- 1 arantius   840 May  2 10:33 resource-from-vm-fx.zip
    -rw-r--r-- 1 arantius 13438 May  2 10:18 storage-from-gm-fx.zip
    -rw-r----- 1 arantius  1288 May  2 10:47 storage-from-tm-cr.zip
    -rw-r--r-- 1 arantius  1289 May  2 10:16 storage-from-tm-fx.zip
    -rw-r----- 1 arantius  1064 May  2 10:43 storage-from-vm-cr.zip
    -rw-r--r-- 1 arantius  1121 May  2 10:10 storage-from-vm-fx.zip

* VM always has one `.user.js` and one `violentmonkey` file, in these exports.
* TM always has one `.user.js`, one `.options.json` and one `.storage.json`.
* GM always has a folder with one `.user.js`, always a `.gm_details.json`, and a `.storage.json` iff there are stored values.
* All the names are mangled differently.
* In all cases, VM and TM never contain any requires or resources in their export.  I guess they hope they're still available for download at the original URL?

**Comment by arantius** [comment]
* Violentmonkey seems to ignore paths; any file anywhere that ends in `.user.js` gets installed, so it imports all other exports.
* Violentmonkey restores its own stored values, but not any other platform's.
* Tampermonkey launches a dialog, which lets you choose what to import, including saying what will update/replace, and what is new.
* Tampermonkey restores its own stored values, but not any other platform's.
* Greasemonkey won't import any other engine's exports (it just silently does nothing).

So I'd like to:

* Put one directory per script; in that the original named `.user.js` file.  Each of the requires and resources, name mangled in case of conflict, with a .json map of original source to possibly-mangled filename.  (This is largely human readable and recoverable with little effort.)  An extra file for the stored values.  An extra file for the settings.
** But only setting values that we explicitly choose to export; no `evalContent`, for example, belongs in the export.
* Prefer that format.  For any `.user.js` that didn't work out that way, try to import that bare file (i.e. import other engine's exports, perhaps lossily).
* Definitely do some kind of status message on completion.
* Maybe do some kind of select-per-script import like TM, instead of the "choose three browse buttons" we've got today.  (This is probably a big enough change to be separate, though.)

**Comment by Sxderp** [comment]
>  (This is probably a big enough change to be separate, though.)
This will necessitate a import page. The original idea was to keep the options such that you could import from the monkey menu when Mozilla finally fixed the popup issue.

**Comment by Sxderp** [comment]
> Greasemonkey won't import any other engine's exports (it just silently does nothing).

That's interesting, when I had tested it I was able to import TM value-store. Perhaps something broke along the way. But the `.json` format should be the same.
