### ISSUE TITLE
Error when uninstalling last script

### ISSUE THREAD

**Issue by arantius** [greasemonkey/greasemonkey#2957]
If you have only one script installed and you uninstall it (specifically, I click "uninstall" then when clicking the back arrow) you get:

     e is not a function rivets.bundled.min.js:6

A failure somewhere in the rivets templating engine.  A second click on the back button works.

**Comment by arantius** [comment]
Update: this is "last script in a section".  So if you have only one "for this tab" or "other", this happens.

**Comment by Sxderp** [comment]
This has to do with using `rv-unless` for the script sections.

https://github.com/greasemonkey/greasemonkey/blob/18e21a4d5d9372e035629eed88e3954f4346322b/src/browser/monkey-menu.html#L30-L31

https://github.com/greasemonkey/greasemonkey/blob/18e21a4d5d9372e035629eed88e3954f4346322b/src/browser/monkey-menu.html#L43-L45

Changing the top `<div>`s to `rv-hide` solves the problem.

**Comment by arantius** [comment]
I'd prefer the behavior of unless (unneeded elements are not in the DOM at all, vs. hidden via CSS). Do you know why?  Unless/if should work, shouldn't they?

**Comment by Sxderp** [comment]
I'm not entirely sure, but this and #2963 might be related to the following:
https://github.com/mikeric/rivets/issues/452#issuecomment-100131921

I haven't done any testing (related to why `rv-if` fails) and I only just now looked up the above issue (doing a search on `rv-if` problems). I only thought of changing the directive because I distinctly remember this working in some mockups (never published) some time ago.

**Comment by arantius** [comment]
That sure looks like a good explanation.
