### ISSUE TITLE
Why do we need all this code in api-provider-source.js

### ISSUE THREAD

**Issue by KOLANICH** [greasemonkey/greasemonkey#2970]
I mean

1 Why do we  generate this file dynamically?
2 Why do we have any logic there, but not on the backend?
3 Why don't we use just a Proxy just translating api calls into messages?

**Comment by KOLANICH** [comment]
@arantius just closing the issue doesn't answer to my questions.

**Comment by Sxderp** [comment]
1. Not all scripts request all the API calls. This is mostly a semantically issue. Any userscript could just re-implement the API functions (that is manually `sendMessage` to the backend) since userscripts are run as Firefox Webextension 'content scripts'. Further, each userscript is in it's own scope and therefore each script needs the functions injected.
2. I'm not sure what you're trying to point out here. The injected code is, for the most part, slim on logic. Each one takes the arguments, perform some conversion such that the backend will understand the data, and then sends a message to the backend.
3. How does this benefit? The `GM` object, with its defined functions/methods, is already converting API calls into messages.

**Comment by KOLANICH** [comment]
1,2,3
I mean we can replace them with a very dumb [Proxy](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Proxy) just returning all the functions asked, the functions are just forwarding the messages, and move all the logic present in some of the functions to backend. I guess the proxy may be smaller than the generated code in the maximum configuration and the same for all the scripts. So no dynamic code generation on each injection, if we could put 2 separate scripts in the same context.

The problem is that I don't know how this would affect memory consumption and performance.

**Comment by Sxderp** [comment]
>  So no dynamic code generation on each injection

Just as clarification. The code isn't dynamically generated on each injection. It's generated when the script is saved or updated. This 'compiled' code is stored and used for injection.

> I mean we can replace them with a very dumb Proxy (GM object will be the proxy) just returning all the functions asked, the functions are just forwarding the messages.

If I'm understanding correctly you're suggesting something like:
```javascript
const GM = {
  'info': {
    /* INFO STUFFS */
  }
};

const handler = {
  get: function(obj, fn) {
    /* I'd inject the below array based on grants */
    const possibleFns = ['getValue', 'setValue'];
    /* No grant. Don't even try */
    if (possibleFns.indexOf(fn) == -1) return;
    return function() {
      return browser.sendMessage({
        'name': 'Api' + fn,
        'data': arguments
      });
    }
  }
};

const GM = new Proxy(baseGM, handler);
```

This seems like an interesting idea but there's some problems I see. For example, when we do some 'post-response' processing (ex. [getValue](https://github.com/greasemonkey/greasemonkey/blob/b582ae8576c7180cd192415c99358fa8a71cd6f9/src/bg/api-provider-source.js#L86-L89) and [getResourceUrl](https://github.com/greasemonkey/greasemonkey/blob/b582ae8576c7180cd192415c99358fa8a71cd6f9/src/bg/api-provider-source.js#L133)). Or when we have to keep callback functions around since they can't be passed to the background. The [notification](https://github.com/greasemonkey/greasemonkey/blob/b582ae8576c7180cd192415c99358fa8a71cd6f9/src/bg/api-provider-source.js#L160-L163) and [xml](https://github.com/greasemonkey/greasemonkey/blob/b582ae8576c7180cd192415c99358fa8a71cd6f9/src/bg/api-provider-source.js#L233-L237) APIs require this.

Conditionals could probably be added to account for the above cases, but if we're adding conditionals for specific APIs then that's already not much different from using separate functions.

**Comment by KOLANICH** [comment]
>If I'm understanding correctly you're suggesting something like

Not quite, I meant no permission-related logic here at all. Just sending messages without any checks, like grants, keeping all the checks are on the backend. If a script has no permission, the promise is rejected.

>Or when we have to keep callback functions around since they can't be passed to the background. The notification and xml APIs require this.

Why not to just use promises?

**Comment by Sxderp** [comment]
> Why not to just use promises?

This only works if there is a single success callback and a single error callback (resolve / reject). But if there are many, which [xhr](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequestEventTarget#Properties) and [notifications](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/notifications#Events) have several, the promise structure does not work. Especially when the callbacks are called 'during' the processing of an action (XHR.onprogress) and not just when finished.

In order to facilitate this functionality all the `on[*]` functions are stored in scope and a port is opened. Each time one of these events occurs in the background a message is sent through the port with the relevant event details. The port then passes it on to the corresponding stored `on[*]` function.

**Comment by arantius** [comment]
This is not a discussion forum.  We have https://groups.google.com/d/topic/greasemonkey-dev/ for a reason.
