### ISSUE TITLE
WebExtension API exposed - deliberately?

### ISSUE THREAD

**Issue by DanMan** [greasemonkey/greasemonkey#2999]
I was just surprised that doing a `console.log(browser)` in a Userscript in Firefox actually showed the Storage API and a few other things, and in a quick test I could store a value and it'd still be there after re-opening  the browser.

Is this supposed to happen or is that a bug? If it's the former, it isolated for each script, right? Otherwise that'd be a security problem, right?

It'd be nice, if we could use that, if it's available in a cross-browser fashion.

**Comment by Sxderp** [comment]
It's a limitation of the version of Firefox WebExtension that GM is built around. 

Mozilla is working on being able to reduce permissions within the UserScript API. There's a bugzilla about it.

**Comment by arantius** [comment]
As mentioned, this was an intentional design decision: given the choices available in the extension API, we elected to strongly isolate all scripts from the pages.  We gave up some isolation between scripts (and between scripts and the extension) as a result.

IMO the scripts that you choose to install are a lot more like extensions you choose to install than pages you choose to browse, so this is the right side to fall on.

**Comment by DanMan** [comment]
So could one script access another one's IndexedDB or not?

**Comment by Sxderp** [comment]
I'm not sure about `browser.storage` but if the script uses the `GM_*Value` apis then the answer is _practically_ no. If a malicious script had the internal UUID of another script then it could retrieve `GM_*Value` content. 

The `UserScript` api would be able to help prevent this.

**Comment by DanMan** [comment]
> If a malicious script had the internal UUID of another script then it could retrieve GM_*Value content.

And that's unique per user/install?

**Comment by Sxderp** [comment]
> And that's unique per user/install?

Per install.
