### ISSUE TITLE
Decrease auto-update upper limit or make it configurable

### ISSUE THREAD

**Issue by zuckel** [greasemonkey/greasemonkey#3000]
The current upper limit for the auto-update interval is 7 days, which is too long for my use case.

I understand that there is no ideal value for every user and use case. What is your take on making this configurable? My preferred approach would be having an optional setting in the script metadata.

**Comment by makyen** [comment]
Your issue is unclear. Do you mean that the maximum configurable period between auto-update checks is 7 days? Or, that the minimum time between auto-update checks on a specific script (or all scripts) is 7 days? Or, something else?

My normal/initial reading of what you're talking about is inconsistent with 7 days being "too long for my use case". Are you saying you don't want user's to be able to have a 7-day interval? If so, that sounds inconsistent with wanting it to be configurable. Please clarify, and edit the issue title to make it clear what the problem is about.

**Comment by Sxderp** [comment]
I think they (as a script author) want to specify within the script metadata the 'max allowable time' between update checks for their (published) script. So when they say configurable they mean configurable _by the author_.

But I'm not sure I see the point in specifying a smaller value. The auto-update process uses how recently the script was updated in order to determine the length of time between checks. If a script updates frequently then it will be checked frequently.

**Comment by zuckel** [comment]
My personal use case is simple: I want certain scripts to be checked at least daily because the underlying pages change frequently.

I was trying to be open about possible solutions, but this only turned out to be vague and confusing, so sorry for that.

**Comment by arantius** [comment]
There is value in software that "just works".  The current update scheme is an attempt at that, and at compromising the traffic generated by update requests against the user experience.

After a new script is auto-updated, it starts checking every three hours!  Each time that this doesn't produce a new version, it will add (approximately, intentionally randomized a little bit) 25% to that delay, so that will mean immediately after an update to a new version, it will check five times in the next 24 hours.  Twice more in the next 24 hours, 12 times total before it starts waiting a week between checks.   As soon as one of those checks produces a new version, it starts over from 3 hours again.

So do you really need to customize that to be even faster?  It feels like a good compromise to me.

**Comment by Cerberus-tm** [comment]
I think this sounds like a great compromise; interesting approach, too.

Even so, I can imagine there being scenarios in which it might be desirable for a user (not author) to set a maximum update interval for certain userscripts, such as for those scripts operating on pages that change frequently and hence might require frequent (but hard to predict) changes in the scripts (as suggested by Zuckel). Maybe this feature shouldn't have a high priority, as there are no doubt more important things to work on; but I would certainly use the setting if it became available at some point in the future.

**Comment by zuckel** [comment]
I guess the current auto-update functionality works sufficiently well for almost all use cases. It probably also works well enough for me, as long as I understand how it works. Adding complexity to the project for this is not warranted. Thanks for the discussion, everyone!
