### ISSUE TITLE
match (escaping ?) bug

### ISSUE THREAD

**Issue by Owyn** [greasemonkey/greasemonkey#3030]
Have this match rule
`// @match		https://*.imgspice.com/*.html`

`https://imgspice.com/fes0h1rvfhbp/_(2).jpg.html` - matches, script runs
`https://imgspice.com/fes0h1rvfhbp/_&#40;2&#41;.jpg.html` - doesn't match, script doesn't run

using GM 4.7 with FF 66.0.3 (64bit)

**Comment by Sxderp** [comment]
This is somewhat more of an issue with the site you're using. First, in regard to resource identifiers the `#` is a special character that signifies the start of the fragment identifier and anything passed this point is not considered part of the "URL". As a result it is never sent to the server and is not used for serving requests (as a caveat, clientside javascript could potentially use it for anything). If this symbol is to be sent to the server it must be url encoded as `%23`. Since anything passed this symbol is not considered part of the URL Greasemonkey does not use that part of the string for matching.

What does this mean for the site you linked? Knowing that anything passed a `#` is not sent to the server I started playing with the URL you provided. It looks like the site ignores anything passed the final path separator ( `/` ) [1]. It's probably just used for SEO or to provide pretty names to users. What you likely want to do is make your match pattern more broad and if that doesn't work you may need some additional checks within the code itself. Alternatively, using an `@include` may work for you. I think it uses the entire URL, as seen by the user, for determining whether a given path matches.

[1] https://imgspice.com/fes0h1rvfhbp/a
