### ISSUE TITLE
How do I install from a locally saved script?

### ISSUE THREAD

**Issue by DumbJoe** [greasemonkey/greasemonkey#3033]
I tried the file:/// trick but all that does it open the script file like a text reader and the extension doesn't install it.....

**Comment by Sxderp** [comment]
Unfortunately `file://` is not going to work. Blame WebExtensions. What needs to be added is an "upload" button of some sort. I thought this was added (can't check atm) but maybe it was only done for bulk.

**Comment by Maybe00** [comment]
Greasemonkey has dropped off from both my phone and laptop.  Trying to reinstall gives me an error message saying it's corrupt. Please do something to fix this as all the scripts I use are now useless.

**Comment by Maybe00** [comment]
Greasemonkey has stopped working on both my phone and laptop.  Trying to reinstall only gives an error message saying it's corrupt. 
I use GM scripts all the time so this is not good.

**Comment by makyen** [comment]
@Maybe00 Your problem is a general Firefox issue that lots of people are having right now with a large number of Firefox extensions. There's nothing Greasemonkey can do about it. The basic issue is that a security certificate Mozilla uses to sign extensions was allowed to expire. The result is that many Firefox extensions are considered invalid and are thus disabled/removed and you are not permitted to re-install.

You can watch [this Firefox bug in Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1548973) and wait for resolution.

Your other alternatives for using Firefox with extensions are:

1. Switch to Developer Edition or Nightly and set `xpinstall.signatures.required` to `false` in `about:config`.
2. [Disable signature checking in the release version of Firefox](https://stackoverflow.com/questions/31952727/how-can-i-disable-signature-checking-for-firefox-add-ons/42403531#42403531). This is a link to a Stack Overflow answer where I describe how to disable Firefox extension signature checking on a per-profile basis.

**Comment by Cerberus-tm** [comment]
@makyen Thank you for the warning! Luckily, I had not been affected yet by this bug. I wonder why not. I had the "studies" thing off, so it couldn't have been a fix from Mozilla.

**Comment by arantius** [comment]
WebExtensions have no programmatic filesystem access.  If you install a local script but then it says `// @require other.js`, we can't open the "other.js" file to also install it, and the script won't work because it will be only partially installed.

**Comment by DumbJoe** [comment]
Ah.

But if the script doesn't open or need any other external scripts that needs to also be installed in greasemonkey, it's all work, yes? Are there any other issues besides this or is that that only hurdle?

Usually when it does require extra scripts, then the author would zip that along with the original script....unless the js file is a url to an external site that it downloads from.....which the author makes no mention in any sort of documentation.....
