### ISSUE TITLE
Fetch requests do not show up in the Network tab of Firefox's Developer Tools

### ISSUE THREAD

**Issue by RudeySH** [greasemonkey/greasemonkey#3071]
While debugging my userscript, I noticed that `fetch` requests are not showing up in the devtools network tab. After some more debugging, I concluded that the requests are really being sent, my script gets a response with a status code and headers. But nothing shows up in the network tab.

Can this get fixed? It's nearly impossible to debug fetch requests if they don't show up.

**Comment by schammy** [comment]
I'm playing around with keepalive fetch requests, and noticed that these requests don't show up in the network tab. Claude.ai clued me in that keepalive must be turned OFF, then they'll show up. Sure enough, that was true.

WHY!?  Chromium shows them either way, Firefox should too! 🤓

**Comment by gaellafond** [comment]
I spent a lot of time figuring out why Firefox was not logging Google Analytics requests. They are sent using `window.fetch`.

I can see the logs from Firefox in Google Analytics, the requests are definitely getting sent. I can also see the requests in Wireshark, but the requests are not shown in Firefox's developer tool.

We are in 2025 now, 5 years after this issue was created. Why is it not fixed yet? Can we re-open this issue?

**Comment by Cerberus-tm** [comment]
Not even in the Multiprocess Browser Console? Control-Shift-J
