### ISSUE TITLE
update intervall - userscripts

### ISSUE THREAD

**Issue by sama77** [greasemonkey/greasemonkey#3081]
Hello, 
can someone tell me how exactly I can influence the interval for the automatic updates of my user scripts?
In my test cases I could not see a schema when it was checked whether a new version was available!

Thank you in advance.
Sylvio

**Comment by Sxderp** [comment]
I don't believe this has been implemented. Nor do I think it will be implemented. If I recall (I could be mixing up some other metavar) @arantius  decided against adding this due to potential malicious intent.

**Comment by sama77** [comment]
Hm, so greasemonkey gets a current version from my server. So I think this is (still) in there. I was only concerned with when he checks to see if there is a new version !?
Thanks for your help.

**Comment by Sxderp** [comment]
GM will check for updates, but those checks are not controllable by the script metadata.

**Comment by sama77** [comment]
OK, so the update behavior is arbitrary and cannot be influenced by Firefox settings?

**Comment by Sxderp** [comment]
Not quite arbitrary, but otherwise correct.

**Comment by sama77** [comment]
It was just about knowing when my script would reload when I made a change. Is used internally and it is nice if you can tell your colleagues that in 2 hours or so, the new version will work.
Thank you for your help.

**Comment by arantius** [comment]
It's not customizable because it's not a single/fixed setting -- it's adaptive.  It will always be between (  https://github.com/greasemonkey/greasemonkey/blob/d8199088cff1e594292b0b65b0796e2cc9dc67be/src/bg/updater.js#L5 ) three hours and seven days, but Greasemonkey picks an interval in that range based on how often it's observed that the script is changing.  When there's a new update, it checks again quickly, then more and more slowly until it hits the maximum window.  If you want to "tell your colleagues" something, tell them how to click the "check for updates" button, and when you release a new version.
