### ISSUE TITLE
GM_config is not working with Firefox

### ISSUE THREAD

**Issue by Purfview** [greasemonkey/greasemonkey#3104]
GM_config is not working with Firefox.
Can it be solved at Greasemonkey's side?

https://github.com/sizzlemctwizzle/GM_config/issues/97
https://github.com/Purfview/IMDb-Scout-Mod/issues/10

**Comment by arantius** [comment]
Are you saying that it's never worked, or recently stopped working?  If the latter, what's the latest version of everything (Firefox, Greasemonkey, etc.) that does work?

**Comment by Purfview** [comment]
Probably never worked in combination Firefox + GM4.
Other monkeys + Firefox works.
GM4 + Waterfox Classic (based on Firefox) works too.

**Comment by arantius** [comment]
It sounds like this almost never worked, has not worked since Firefox 57.0.1 -- over three years ago.

After some quick poking, it seems like simply not setting any source works fine:

```js
// ==UserScript==
// @name     iframe contentDocument
// @version  1
// @grant    none
// ==/UserScript==

var iframe = document.createElement('iframe');
iframe.addEventListener('load', function() {
  try {
    let d = this.contentDocument;
    console.log(1, d);
    let b = d.body;
    console.log(2, b);
    let h = d.createElement('h1');
    h.textContent = 'It works!';
    b.appendChild(h);
  } catch (e) { console.error(e); }
});
document.body.appendChild(iframe);
```

![image](https://user-images.githubusercontent.com/84729/106076509-ae1b5d80-60dd-11eb-9d3a-c56275b37c94.png)

So I'm inclined to close this "working as intended".

**Comment by Purfview** [comment]
Thanks for fix suggestion, it will be fixed at GM_config side.
