### ISSUE TITLE
Version 4.11 update broke musicbrainz discogs import script

### ISSUE THREAD

**Issue by eharris** [greasemonkey/greasemonkey#3106]
My instance of firefox on Debian Buster updated to 4.11 yesterday, and now https://raw.githubusercontent.com/murdos/musicbrainz-userscripts/master/discogs_importer.user.js is not working anymore.

The info panel says that the script is enabled, but it is no longer working, and not sure how to go about debugging further.

I should also mention that my version of firefox-esr also got updated to 78.7.0esr-1~deb10u1 (from security), so it is possible that the firefox update caused the problem rather than greasemonkey.

I have tried downgrading both firefox-esr to 78.5.0esr-1~deb10u1 and greasemonkey to 4.10, but the script still isn't working, so I'm not sure what the issue is, or which one (or if both) broke it.  So reporting here in case it's a greasemonkey problem.

**Comment by arantius** [comment]
Are you the author of this script?  https://wiki.greasespot.net/Greasemonkey_Manual:Getting_Help

But you also said you downgraded to 4.10 and that didn't help, so I don't believe the problem is on our side.

**Comment by eharris** [comment]
No, I'm a user of the script.

You may be right that it's not a greasemonkey issue.  There's some discussion that suggests that discogs may have changed something on their site that broke the script, but haven't been able to confirm that yet.

**Comment by eharris** [comment]
I've since tested this script on Violentmonkey on the same browser, and it still works there.  So only seems to be an issue with Greasemonkey.

**Comment by Cerberus-tm** [comment]
Is it possible that your previously used GM 3.x?

**Comment by eharris** [comment]
I doubt it.  I use that browser pretty much every day and it had auto-update enabled, which is how it got updated to 4.11 and broke.

**Comment by StigNygaard** [comment]
> The info panel says that the script is enabled, but it is no longer working,

How "not working"?
I just installed script in FF 85.0.1 with GM 4.11, and both "Import into MB" and "Search in MB" buttons appers on a Discogs release pages.
I haven't tried actually running an import yet, but that part often fails in a period after either Discogs or MusicBrainz has made changes to their sites (I have had the script installed before).
In general you should always contact script author first. Most likely problem is related to changes on Discogs or MusicBrainz sites. If you are not a skilled javascript/userscript developer yourselves, the author of the script will probably be the best to find out why script fails.
In general userscripts often fails when the sites they run on changes. GM is not to blame for that, and you cannot expect GM developers to investigate errors unless you have done a prior analysis showing it most likely is caused by changes in GM.

**Comment by eharris** [comment]
Not working in that none of the links that should show up for musicbrainz actions show up, including the link to import.

**Comment by eharris** [comment]
At this point, it looks like this may be due to discogs messing with their site, so this may not be a greasemonkey issue.

**Comment by jesus2099** [comment]
It may be linked to https://github.com/greasemonkey/greasemonkey/issues/3111 that make MASS MERGE RECORDINGS fail to send POST requests to MusicBrainz.

**Comment by eharris** [comment]
I agree, this has ended up seeming like it is an issue specific to the site, rather than with greasemonkey.  Closing.
