### ISSUE TITLE
Newer JS operators ("?.", "??") break indenting/coloring in code editor

### ISSUE THREAD

**Issue by istarogh** [greasemonkey/greasemonkey#3115]
In Greasemonkey's built-in code editor, using the [optional chaining operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) (?.) or the [nullish coalescing operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator) (??) at any point in a script breaks indentation and syntax coloring for the rest of the script.  The exact way in which it breaks depends on the specifics of the surrounding expression; I've seen this cause the rest of the script to be treated as a comment, a string, or a template literal.

**Comment by istarogh** [comment]
Updating [/third-party/codemirror/mode/javascript/javascript.js](../blob/master/third-party/codemirror/mode/javascript/javascript.js) to the latest version thereof over at [github/codemirror/CodeMirror/blob/master/mode/javascript/javascript.js](https://github.com/codemirror/CodeMirror/blob/master/mode/javascript/javascript.js) should fix this, but I'm afraid I'm way too new at this to know how to do so myself, or more importantly, know whether doing so might break something else.

**Comment by arantius** [comment]
AFAICT https://github.com/greasemonkey/greasemonkey/commit/591296565bde44a5b62894d4571549bc58fddeb7 fixes this.

**Comment by arantius** [comment]
This should be done.  I could use your help testing this!  Checkout or download Greasemonkey's source code, then follow [the documentation](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension#installing) for installing an extension during development.  As far as I know this will break installed scripts, so you should [use about:profiles](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles#w_manage-profiles-when-firefox-is-open) to create and launch a new blank Firefox profile to do so, rather than overwriting your existing Greasemonkey install.  (Maybe take a Greasemonkey backup first to be safe.)

Any testing results, positive or negative, would be great.

**Comment by istarogh** [comment]
Looks good to me.  I installed the current code as a temporary add-on per that documentation, and as a minimal initial test, made a new userscript containing just

`const x = 1 || 2;`
`const y;`

and the `y` variable name remained blue upon replacing the `||` with a `??`, whereas in the live version, making the same script and then replacing the `||` with a `??` turns the `y` black.

As a more realistic test I then added a strategic `?.` to an existing script of mine and it worked fine, whereas doing so makes all subsequent coloring very wonky in live.

BTW, I didn't want to bother making a new profile, so I did this on a laptop I rarely use, and FWIW it actually did not break installed scripts.
