### ISSUE TITLE
Native support for script configuration like Stylus/Stylish

### ISSUE THREAD

**Issue by ghost** [greasemonkey/greasemonkey#3122]
So this would essentially bring [odyniec/MonkeyConfig](https://github.com/odyniec/MonkeyConfig) into core.

**Comment by makyen** [comment]
Note: the repository, [odyniec/MonkeyConfig](https://github.com/odyniec/MonkeyConfig), which appears to be the one mentioned in the initial comment, was last updated 8 years ago, has no license, 3 open PRs from 2017, 5 open issues, and no closed PRs or issues. The images in the README which should show a examples of what it looks like are dead, and have been since at least 2019 (one of the open issues). There is an image of a popup it creates in [its issue 3](https://github.com/odyniec/MonkeyConfig/issues/3). None of the issues or PRs have any interaction by the repository owner. In other words, the repository appears abandoned and has no license for the code, so it's impossible for someone else to resurrect it.

This comment isn't intended as weighing in either positively or negatively on this feature request. It's just providing information as to the specific example which has been mentioned, so people can find the mentioned, but not linked, repository, but provide enough of a summary so that people don't need to expend the time looking through the repo.

**Comment by SNDST00M** [comment]
Perhaps we could look at [`GM_config`](https://github.com/sizzlemctwizzle/GM_config/) which also does offer a UI.

**Comment by chocolateboy** [comment]
Related: https://github.com/violentmonkey/violentmonkey/issues/414

**Comment by SNDST00M** [comment]
Where is the Tampermonkey issue for configuration?

**Comment by arantius** [comment]
Much like the linked VM issue, this is something I think is best done in "user space" (i.e. a user script) rather than "kernel space" (i.e. the user script manager itself).
