### ISSUE TITLE
Add a `@match-element` userscript tag that fires on `document_idle`

### ISSUE THREAD

**Issue by SNDST00M** [greasemonkey/greasemonkey#3123]
## Feature description

I'd like a `@match-element` tag that makes a script run on pages with an element. For obvious reasons, this should perhaps interact with `@run-at` (running when the `run-at document_idle` event is dispatched at the earliest).

## Context

I have a userscript that scans for elements manually on all pages. This could easily be replaced by a `@match-element`.

## Use cases

Where custom widgets such as Twitter, Discord, Soundcloud etc are present on a page, they could be automatically replaced using `@match-element`.

**Comment by makyen** [comment]
Implementing this request would require loading a content script into *every page* to search for the requested elements. That's a substantial performance hit for users. This would also be substantial additional code in order to trigger userscript load at new times and under new conditions (i.e. not based only on the primary URL used for the page/frame and the load/not load decision able to be made from within the background script when the request for the page is first made).

**Comment by Ferk** [comment]
> Implementing this request would require loading a content script into every page to search for the requested elements. That's a substantial performance hit for users.

But that performance hit is already happening when you have such scripts. That's the point.

Do you see an alternative approach for lowering the performance hit that currently occurs in the situation when the user has multiple scripts of that type (which do need to act on all pages that contain a specific tag)?

The benefit of having this in the script management engine is that it would only needs to load the scripts when needed. The background script only needs to do a search at all if there are any scripts that use this feature. It could also be combined with `@match` (so it only needs to search for the element in all pages if it's `@match *://*/*`) and it only runs the script if both `@match` and `@match-element` are satisfied.
