### ISSUE TITLE
Please document @version, maybe expose a version-checking function

### ISSUE THREAD

**Issue by adamhotep** [greasemonkey/greasemonkey#3154]
The current documentation for [`@version`](https://wiki.greasespot.net/Metadata_Block#@version) in the metadata block is pretty sparse:

> ### @​version
> Example:
> ```// @version 1```

I'd like to know what version schemes are supported (e.g. [semantic versioning](https://semver.org/) 2.0). 

Since parsing this for the auto-update functionality requires being able to know that 1.9.3 < 1.10.0, it might additionally make sense to expose the comparison function to userscripts, e.g. `GM.minVersion(GM.info.version, "1.10.0")` would be true when the current script's version is 1.10.0 or later.

**Comment by arantius** [comment]
This is a good point.  Before I/anyone finds time to completely update the documentation:

Greasemonkey doesn't care what is here, except that Greasemonkey uses the library compare-versions ( https://github.com/omichelsen/compare-versions ) library in order to determine when an update has a higher version.  So, read those docs.

Though IMNSHO https://www.greenwoodsoftware.com/less/faq.html#version is a good versioning policy, and likely applies to most user scripts.

**Comment by adamhotep** [comment]
Exposing `compareVersions()` (which returns `1`, `0`, or `-1`) from compare-versions as `GM.compareVersions()` would work for me.

I don't object to integer-based versions, but I personally prefer to connote impact with major and minor versions.

**Comment by arantius** [comment]
https://wiki.greasespot.net/index.php?title=Metadata_Block&diff=8532&oldid=8421
