### ISSUE TITLE
Updating caption on GM.registerMenuCommand

### ISSUE THREAD

**Issue by SpyderCoder** [greasemonkey/greasemonkey#3157]
I've been fiddling around with Greasemonkey and I'm wondering if there's something that I've missed in the documentation where you can update the caption on a menu command. I think I might just end up using a GM.notification or alert. Here's some code I've written. The variable updates but the caption in the menu doesn't.

```
// ==UserScript==
// @name		GMTestScript
// @version		1
// @grant 	GM.registerMenuCommand
// @grant		GM.getValue
// @grant		GM.setValue
// @include *
// @description My Greasemonkey coding playground
// ==/UserScript==

let playSound;
let soundLabelOption;

(async () => {
  playSound = await GM.getValue("playSound");
  soundLabelOption = await GM.getValue("soundLabelOption");
  
  if(playSound === undefined) {
  	await GM.setValue("playSound", true);
    console.log("undefined");
  }
  if(soundLabelOption === undefined) {
  	await GM.setValue("soundLabelOption", "Disable Sound");
    console.log(soundLabelOption);
  }
  
  GM.registerMenuCommand(soundLabelOption, () => setSound());
})();

const setSound = async() => {
  playSound = await GM.getValue("playSound");
  
  switch(playSound) {
    case true:
      await GM.setValue("soundLabelOption", "Enable Sound");
      console.log("disabled");
      await GM.setValue("playSound", false);
      break;
    case false:
      await GM.setValue("soundLabelOption", "Disable Sound");
      console.log("enabled");
      await GM.setValue("playSound", true);
      break;
  }
  
  console.log(soundLabelOption);
}
```

**Comment by arantius** [comment]
There is no feature to change the caption of an already-registered menu command.

**Comment by makyen** [comment]
Even if there was the capability to change the caption, there's no way for Greasemonkey to know that you're trying to change an already existing menu command instead of registering a new command. While Greasemonkey _might_ be able to assume you were trying to change an existing one if you passed the same function to `GM.registerMenuCommand()` as you did to create the original, you're passing an anonymous arrow function, so there's no way for the API to know the menu commands are related, at all.

Note: it's debatable if calling `GM.registerMenuCommand()` with the same function as an existing menu command should cause an update to the existing menu command's caption or create a new entry. I could see people wanting either capability.

**Comment by SpyderCoder** [comment]
I actually did try calling the `GM.registerMenuCommand()` in the async function but wasn't all too surprised when it added another menu command with the updated caption each time it was called. Maybe something like `GM.updateMenuCommand()` might be a nice feature to have. Till then I've made use of the `GM.notification()` as an alternative way of showing the setting change.

**Comment by sjehuda** [comment]
I think this is an important feature - and also use the Greasemonkey logo as indicator of events - which would allow to neglect making of simple extensions by userscript.

For instance, an RSS discovery button has been made for a web browser I use.
There are two elements of it:
1) Menu, which Greasemonkey covers too.
2) Indication icon that RSS has been found.

An icon indicator would be good as well as changing caption (e.g. caption "on" when off, and caption "off" when on, instead of toggle on/off).
