### ISSUE TITLE
GreaseMonkey vs ViolentMonkey

### ISSUE THREAD

**Issue by stokito** [greasemonkey/greasemonkey#3163]
Maybe this was answered somewhere but I didn't found.
Why the GreaseMonkey is still doesn't support Chrome?
The TamperMonkey is closed source and there is yet another one ViolentMonkey created.
This is so confusing

**Comment by erosman** [comment]
General Information:
At the moment, Chrome store doesn't accept manifest V2 extensions and manifest V3 doesn't support userscript YET.

See also: [Userscript managers support](https://developer.chrome.com/docs/extensions/mv3/known-issues/#userscript-managers-support)

**Comment by Vampire** [comment]
Since when is TamperMonkey closed source?
It is GPLv3 licensed: https://github.com/Tampermonkey/tampermonkey

**Comment by Vampire** [comment]
And how did TamperMonkey then make it into the Chrome store if it does not allow manifest V2 extensions?
https://github.com/Tampermonkey/tampermonkey/blob/master/build_sys/manifest.json.google.com

**Comment by bunglegrind** [comment]
> Since when is TamperMonkey closed source?

5 june 2018, I suppose...well, maybe 6 june

**Comment by Vampire** [comment]
Oh, sorry, missed that

**Comment by erosman** [comment]
> And how did TamperMonkey then make it into the Chrome store if it does not allow manifest V2 extensions? https://github.com/Tampermonkey/tampermonkey/blob/master/build_sys/manifest.json.google.com#L2

Chrome store had stopped accepting new MV2 extensions. The ones already on store were supposed to covert to MV3 by Jan 2023 but the deadline was extended.

[The transition of Chrome extensions to Manifest V3](https://developer.chrome.com/blog/mv2-transition/)
> There are two key dates for the phase-out:
> 
> - **January 17, 2022:** New Manifest V2 extensions will no longer be accepted by the Chrome Web Store. Developers may still push updates to existing Manifest V2 extensions, but no new Manifest V2 items may be submitted.
> 
> - **January 2023:** The Chrome browser will no longer run Manifest V2 extensions. Developers may no longer push updates to existing Manifest V2 extensions.

[Chrome Extensions Manifest V2 support timeline - Chrome Developers](https://developer.chrome.com/docs/extensions/migrating/mv2-sunset/)

![image](https://user-images.githubusercontent.com/6458876/233465102-17d02a82-fe07-4461-9c5e-5b3f3baed94c.png)


---
> Since when is TamperMonkey closed source? It is GPLv3 licensed: https://github.com/Tampermonkey/tampermonkey

[tampermonkey](https://github.com/Tampermonkey/tampermonkey)

> This repository contains the source of the Tampermonkey extension up to version 2.9. All newer versions are distributed under a proprietary license.

Tampermonkey version 2.9 dated 2012-12-28
Tampermonkey current version 4.18.1

**Comment by jelabarre59** [comment]
All the more reason NOT to use Google Chrome, AKA MSIE6-revisited (or anything Chromium-based)

**Comment by sjehuda** [comment]
On Thu, 20 Jul 2023 15:36:36 -0700
"James E. LaBarre" ***@***.***> wrote:

> All the more reason NOT to use Chrome, AKA MSIE6-revisited (or
> anything Chromium-based)
> 

I agree with your MSIE6 statement, which was obvious to come.

Sometimes, we ask, "Why would we want to have another software that
(almost) does the same thing?", so the answer is less unfair politics
that come with power centralization.

So, while I have never installed Chromium based products (except
Falkon, which might be using WebKit, but I'm not sure), I'm in favor of
making Greasemonkey available for that product too, preferably outside
of its store.

And I know that this web browser is just bad. See below.

* * *

> Chrome, AKA MSIE6-revisited

https://www.moparisthebest.com/images/chrome.png

For this reason I'm moving away to Germany or other Nordic country or
some USA-occupied territory, namely because lawyers and private equity
firms in Middle East are not of the brightest in the world, to say the
least, and they don't care for privacy, even though they are the ones
who need to care the most.

Let me know if you have a good firm in mind.

Otherwise, I'll go back to the farming business.
