### ISSUE TITLE
[Bug] Setting the wrong user @match prevents opening the menu

### ISSUE THREAD

**Issue by esperecyan** [greasemonkey/greasemonkey#3171]
If the incorrect syntax “user@match” is set, then the Greasemonkey menu will not open at all.

It is still possible to recover from this situation, as Greasemonkey menus can still be opened in `about:addons` and so on.

> Error: @match: Invalid host specified. MatchPattern.js:81:11

https://github.com/greasemonkey/greasemonkey/blob/11e340b4dadee868191e72a3ef888f75c6eabbc1/third-party/MatchPattern.js#L80-L82

**Comment by arantius** [comment]
For a bit more detail:  This bug comes through https://github.com/greasemonkey/greasemonkey/blob/11e340b4dadee868191e72a3ef888f75c6eabbc1/src/browser/monkey-menu.js#L331 calling https://github.com/greasemonkey/greasemonkey/blob/11e340b4dadee868191e72a3ef888f75c6eabbc1/src/user-script-obj.js#L149 on each script, which relies on https://github.com/greasemonkey/greasemonkey/blob/11e340b4dadee868191e72a3ef888f75c6eabbc1/src/user-script-obj.js#L173 .

If this last helper, `_testCludes()` finds a match from includes, excludes, or any match before the invalid user match nothing happens.  (This is effectively the workaround, except that comes from `runsOn()` and causes it to never call the helper at all.)  If none of these cases occur, we get to the bottom of `_testCludes()` which involves attempting to parse the (user) match string into a match object, which previously failed and was uncaught.  Any invalid user match, not just the literal `user@match` will trigger this failure, if the code gets this far.

**Comment by arantius** [comment]
I've checked with the above commit that adding a bad match in the script editor still gives an error, and installing a script with a bad match (e.g. https://gist.github.com/arantius/d8fadc5affd40fa5acdff34925189965 ) still gives an error, as desired in both cases.

**Comment by arantius** [comment]
This should be done.  I could use your help testing this!  Checkout or download Greasemonkey's source code, then follow [the documentation](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension#installing) for installing an extension during development.  As far as I know this will break installed scripts, so you should [use about:profiles](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles#w_manage-profiles-when-firefox-is-open) to create and launch a new blank Firefox profile to do so, rather than overwriting your existing Greasemonkey install.  (Maybe take a Greasemonkey backup first to be safe.)

Any testing results, positive or negative, would be great.

**Comment by esperecyan** [comment]
Thanks for the fix!　I was able to confirm that can open the menu with the incorrect user @match by testing the following steps.

1. In Greasemonkey 4.11, adds `https://*example.com/*` to user @match.
1. Confirmed that the menu no longer opens.
1. Installs 8bd283ff3aaf7629c2eaf2057b51e1a4c547a35b.
1. Confirmed that can open the menu and can remove incorrect @match.
