### ISSUE TITLE
No scrollbar when too many userscript commands

### ISSUE THREAD

**Issue by iampradip** [greasemonkey/greasemonkey#3177]
When userscript commands page is full with 20+ userscript menu commands, rest of them get hidden and there is no scrollbar to find them.

**Comment by arantius** [comment]
This should be done.  I could use your help testing this!  Checkout or download Greasemonkey's source code, then follow [the documentation](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension#installing) for installing an extension during development.  As far as I know this will break installed scripts, so you should [use about:profiles](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles#w_manage-profiles-when-firefox-is-open) to create and launch a new blank Firefox profile to do so, rather than overwriting your existing Greasemonkey install.  (Maybe take a Greasemonkey backup first to be safe.)

Any testing results, positive or negative, would be great.
